import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,unlink,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initialize,runBatch,readback,liveTransport} from './runner.mjs';
import {APPROVED_AT,EXPIRES_AT,TRIAL,readiness,payload,validateManifest,CAP_NUSD} from './policy.mjs';
import {MODEL,digest,candidateArtifact,validateArtifact,validateOutput,difference} from '../../apps/web/intro-candidate.mjs';
const manifest=JSON.parse(await readFile(new URL('./sources.json',import.meta.url)));
const preflight={trial:TRIAL,taxFeeCeilingNusd:693250000,credentialBindingVerified:true,globalStandardVerified:true,priorStateConfirmedAbsent:true,soleExecutionTask:true,executionTaskId:'synthetic-task',reviewedHead:'a'.repeat(40),evidence:'SYNTHETIC ONLY'};
const clock=()=>APPROVED_AT+1000;
const output=s=>({candidate:s.fields.intro_description,reason:'Preserve the supported introduction.',citations:[{field:'intro_description',quote:s.fields.intro_description}]});
async function fixture(t){const parent=await mkdtemp(join(tmpdir(),'intro-r1-')),root=join(parent,'ledger');t.after(()=>rm(parent,{recursive:true,force:true}));await initialize(root,manifest,preflight,clock());return {root,preflight,clock,manifestHash:await digest(manifest)};}
function transport(calls,mutate){return async(kind,body,id)=>{calls.push({kind,body,id});const result={id:'resp_fixture',model:MODEL,status:'completed',service_tier:'default',usage:{input_tokens:5001,output_tokens:100,total_tokens:5101},output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(output(manifest.cases[0].source))}]}]};if(mutate)mutate(result);return {requestId:id,body:result};};}
test('one R1 source, one generation, full dollar reserved before dispatch; no count or replay',async t=>{const args=await fixture(t),calls=[],fake=transport(calls);args.transport=async(...v)=>{const r=await readback(args.root);assert.equal(r.calls,1);assert.equal(r.reserved_nusd,CAP_NUSD);return fake(...v);};const r=await runBatch(args);assert.equal(r.state,'complete');assert.equal(r.calls,1);assert.equal(r.reserved_nusd,CAP_NUSD);assert.equal(calls[0].kind,'generate');assert.ok(Buffer.byteLength(JSON.stringify(calls[0].body))<=4096);await runBatch(args);assert.equal(calls.length,1);const a=JSON.parse(await readFile(join(args.root,'public-intro.candidate.json')));assert.equal(a.trial,TRIAL);assert.equal(a.schema_version,2);assert.equal((await validateArtifact(a,manifest.cases[0].source)).mode,'synthetic');assert.equal(a.receipt.input_tokens,5001);});
for(const [name,patch] of [['missing activation',{preflight:null}],['expired',{clock:()=>EXPIRES_AT}],['global standard unverified',{preflight:{...preflight,globalStandardVerified:false}}],['unbound',{preflight:{...preflight,credentialBindingVerified:false}}],['tax exceeds cap',{preflight:{...preflight,taxFeeCeilingNusd:693250001}}],['unknown prior state',{preflight:{...preflight,priorStateConfirmedAbsent:false}}],['multiple execution tasks',{preflight:{...preflight,soleExecutionTask:false}}]])test(name+' prevents dispatch',async t=>{const args=await fixture(t);let calls=0;await assert.rejects(runBatch({...args,...patch,transport:async()=>calls++}));assert.equal(calls,0);assert.equal((await readback(args.root)).calls,0);});
test('timeout permanently consumes one slot and full dollar across restarts',async t=>{const args=await fixture(t);let calls=0;args.transport=async()=>{calls++;throw Error('unknown');};await assert.rejects(runBatch(args),/UNKNOWN_STOP/);const r=await readback(args.root);assert.equal(r.calls,1);assert.equal(r.reserved_nusd,CAP_NUSD);await assert.rejects(runBatch(args),/PRIOR_DISPATCH/);await assert.rejects(initialize(args.root,manifest,preflight,clock()),/EXISTING_STATE/);assert.equal(calls,1);});
test('legacy, partial and missing journals cannot open a new budget',async t=>{const args=await fixture(t);await writeFile(join(args.root,'journal.jsonl'),JSON.stringify({type:'initialized',trial:'INTRO-TRIAL-01',manifest_hash:args.manifestHash})+'\n');assert.equal((await readback(args.root)).state,'LEGACY_STOP_READBACK_ONLY');await assert.rejects(runBatch({...args,transport:async()=>assert.fail()}),/MANIFEST_DRIFT/);await assert.rejects(initialize(args.root,manifest,preflight,clock()),/EXISTING_STATE/);await unlink(join(args.root,'journal.jsonl'));await assert.rejects(initialize(args.root,manifest,preflight,clock()),/EXISTING_STATE/);await assert.rejects(readback(args.root),/ENOENT/);});
test('absent root is not authorization, old manifest rejected, bytes are not tokens',async t=>{const parent=await mkdtemp(join(tmpdir(),'intro-absent-'));t.after(()=>rm(parent,{recursive:true,force:true}));const r=await readback(join(parent,'absent'));assert.equal(r.state,'ABSENT_NOT_AUTHORIZATION');assert.equal(r.calls,null);assert.throws(()=>validateManifest({...manifest,trial:'INTRO-TRIAL-01'}),/INVALID_MANIFEST/);assert.throws(()=>validateManifest({...manifest,cases:[...manifest.cases,...manifest.cases]}),/INVALID_MANIFEST/);const large=structuredClone(manifest.cases[0].source);large.fields.intro_description='界'.repeat(1500);assert.throws(()=>payload(large),/PAYLOAD_BYTE_LIMIT/);});
test('manifest and activation task drift prevent dispatch',async t=>{const args=await fixture(t);await assert.rejects(runBatch({...args,manifestHash:'wrong',transport:async()=>assert.fail()}),/MANIFEST_DRIFT/);await assert.rejects(runBatch({...args,preflight:{...preflight,executionTaskId:'different'},transport:async()=>assert.fail()}),/MANIFEST_DRIFT/);});
test('R1 receipt accepts measured input over4000; legacy remains unchanged; source/quote binding',async()=>{const s=manifest.cases[0].source,r={mode:'synthetic',model:MODEL,response_id:'resp_test',request_id:'req_test',input_tokens:5001,output_tokens:100};const a=await candidateArtifact(s,output(s),r,TRIAL);assert.equal((await validateArtifact(a,s)).changed,false);const old=await candidateArtifact(s,output(s),r);await assert.rejects(validateArtifact(old,s),/RECEIPT/);await assert.rejects(validateArtifact({...a,receipt:{...r,input_tokens:400001}},s),/RECEIPT/);await assert.rejects(validateArtifact(a,{...s,version:'0'.repeat(64)}),/STALE/);assert.throws(()=>validateOutput({...output(s),citations:[{field:'intro_description',quote:'invented'}]},s),/UNBOUND/);const d=difference('hello old','hello new');assert.equal(d.prefix+d.removed+d.suffix,'hello old');assert.equal(d.prefix+d.added+d.suffix,'hello new');});
test('transport has only global generation endpoint, proxy placeholder pass-through, no redirects or retry',async t=>{const previous=globalThis.fetch;t.after(()=>globalThis.fetch=previous);const requests=[];globalThis.fetch=async(url,options)=>{requests.push({url,options});return new Response('{}');};const send=liveTransport(()=>'synthetic-proxy-placeholder'),body=payload(manifest.cases[0].source);await assert.rejects(send('count',body,'id'),/INVALID_REQUEST_KIND/);assert.equal(requests.length,0);await send('generate',body,'id');assert.equal(requests[0].url,'https://api.openai.com/v1/responses');assert.equal(requests[0].options.headers.Authorization,'Bearer synthetic-proxy-placeholder');assert.equal(requests[0].options.redirect,'error');assert.deepEqual(JSON.parse(requests[0].options.body),body);assert.equal(body.service_tier,'default');assert.equal(body.max_output_tokens,1500);assert.equal(body.background,false);assert.deepEqual(body.tools,[]);assert.equal(body.previous_response_id,undefined);assert.equal(body.conversation,undefined);globalThis.fetch=async()=>{throw Error('network fixture');};await assert.rejects(send('generate',body,'id'));});
test('concurrent invocation cannot dispatch twice',async t=>{const args=await fixture(t);let release,entered;const started=new Promise(r=>entered=r),pause=new Promise(r=>release=r);let calls=0;const first=runBatch({...args,transport:async()=>{calls++;entered();await pause;throw Error('unknown');}});const stopped=assert.rejects(first,/UNKNOWN_STOP/);await started;await assert.rejects(runBatch({...args,transport:async()=>calls++}),/EEXIST/);release();await stopped;assert.equal(calls,1);});
for(const [name,mutate] of [['usage mismatch',b=>b.usage.total_tokens++],['input bound',b=>b.usage.input_tokens=400001],['output bound',b=>b.usage.output_tokens=1501],['truncated',b=>b.status='incomplete'],['unbound quote',b=>{const o=JSON.parse(b.output[0].content[0].text);o.citations[0].quote='invented';b.output[0].content[0].text=JSON.stringify(o);}],['wrong model',b=>b.model='other'],['priority tier',b=>b.service_tier='priority'],['unexpected tool',b=>b.output.push({type:'function_call'})]])test(name+' retains full reservation without artifact or replay',async t=>{const args=await fixture(t),calls=[];args.transport=transport(calls,mutate);await assert.rejects(runBatch(args),/UNKNOWN_STOP/);await assert.rejects(readFile(join(args.root,'public-intro.candidate.json')),/ENOENT/);assert.equal((await readback(args.root)).reserved_nusd,CAP_NUSD);await assert.rejects(runBatch(args),/PRIOR_DISPATCH/);assert.equal(calls.length,1);});
test('SIGKILL retains full dollar, only slot and crash lock',async t=>{const {spawn}=await import('node:child_process');const args=await fixture(t);const script=`import {runBatch} from ${JSON.stringify(new URL('./runner.mjs',import.meta.url).href)};await runBatch({...${JSON.stringify({...args,clock:undefined})},clock:()=>${APPROVED_AT+1000},transport:async()=>{process.stdout.write('RESERVED\\n');await new Promise(()=>{setInterval(()=>{},1000);});}});`;const child=spawn(process.execPath,['--input-type=module','-e',script],{stdio:['ignore','pipe','pipe']});t.after(()=>child.kill('SIGKILL'));await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('child timeout')),5000);child.stdout.once('data',()=>{clearTimeout(timer);resolve();});child.once('exit',code=>{clearTimeout(timer);reject(Error('early exit '+code));});});const exit=new Promise(resolve=>child.once('exit',(code,signal)=>resolve(signal)));child.kill('SIGKILL');assert.equal(await exit,'SIGKILL');const r=await readback(args.root);assert.equal(r.calls,1);assert.equal(r.reserved_nusd,CAP_NUSD);await assert.rejects(runBatch({...args,transport:async()=>assert.fail()}),/EEXIST/);});
