import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,unlink,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initialize,runBatch,readback,liveTransport} from './runner.mjs';
import {APPROVED_AT,EXPIRES_AT,LIVE_READINESS,readiness,payload} from './policy.mjs';
import {MODEL,digest,candidateArtifact,validateArtifact,validateOutput,difference} from '../../apps/web/intro-candidate.mjs';
const manifest=JSON.parse(await readFile(new URL('./sources.json',import.meta.url)));
const preflight={countPriceNusdIncludingTax:100,taxNumerator:1,taxDenominator:1,credentialBindingVerified:true,evidence:'SYNTHETIC TEST ONLY; no pricing or binding evidence'};
const clock=()=>APPROVED_AT+1000;
const output=s=>({candidate:s.fields.intro_description,reason:'Preserve the supported introduction.',citations:[{field:'intro_description',quote:s.fields.intro_description}]});
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'intro-test-'));t.after(()=>rm(root,{recursive:true,force:true}));await initialize(root,manifest);return {root,preflight,clock,manifestHash:await digest(manifest)};}
function transport(calls,override){return async(kind,body,id)=>{calls.push({kind,body,id});if(override)return override(kind,body,id);if(kind==='count')return {body:{object:'response.input_tokens',input_tokens:500}};const source=manifest.cases[(calls.length/2)-1].source;return {requestId:id,body:{id:'resp_fixture',model:MODEL,status:'completed',service_tier:'default',usage:{input_tokens:500,output_tokens:100,total_tokens:600},output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(output(source))}]}]}};};}
test('fixed three sources complete with six calls and durable reservations before dispatch; no replay',async t=>{const args=await fixture(t),calls=[];const fake=transport(calls);args.transport=async(...v)=>{const r=await readback(args.root);assert.equal(r.calls,calls.length+1);return fake(...v);};const r=await runBatch(args);assert.equal(r.calls,6);assert.equal(r.state,'complete');assert.equal(r.reserved_nusd,29250300);for(let i=0;i<6;i+=2)assert.deepEqual(calls[i].body,calls[i+1].body);assert.equal(new Set(calls.map(c=>c.body.input)).size,3);await runBatch(args);assert.equal(calls.length,6);for(const c of manifest.cases){const a=JSON.parse(await readFile(join(args.root,c.id+'.candidate.json')));assert.equal((await validateArtifact(a,c.source)).mode,'synthetic');}});
for(const [name,patch] of [['unknown pricing',{preflight:LIVE_READINESS}],['expired',{clock:()=>EXPIRES_AT}],['unbound',{preflight:{...preflight,credentialBindingVerified:false}}],['cost cap',{preflight:{...preflight,countPriceNusdIncludingTax:1e9}}]])test(name+' blocks before any dispatch',async t=>{const args=await fixture(t);let calls=0;await assert.rejects(runBatch({...args,...patch,transport:async()=>calls++}));assert.equal(calls,0);assert.equal((await readback(args.root)).calls,0);});
for(const [name,reply] of [['timeout',()=>{throw Error('fixture timeout');}],['oversized input',()=>({body:{object:'response.input_tokens',input_tokens:4001}})],['missing count',()=>({body:{}})]])test(name+' retains reservation and prohibits replay',async t=>{const args=await fixture(t),calls=[];args.transport=transport(calls,reply);await assert.rejects(runBatch(args),/UNKNOWN_STOP/);assert.equal((await readback(args.root)).calls,1);await assert.rejects(runBatch(args),/PRIOR_DISPATCH/);assert.equal(calls.length,1);});
test('unknown generation consumes second slot and keeps full cost',async t=>{const args=await fixture(t),calls=[];args.transport=transport(calls,kind=>{if(kind==='count')return {body:{object:'response.input_tokens',input_tokens:500}};throw Error('unknown');});await assert.rejects(runBatch(args),/UNKNOWN_STOP/);assert.equal((await readback(args.root)).reserved_nusd,9750100);assert.equal(calls.length,2);await assert.rejects(runBatch(args),/PRIOR_DISPATCH/);});
test('manifest drift and existing lock prohibit dispatch; marker prevents journal reset',async t=>{const args=await fixture(t);let calls=0;args.transport=async()=>calls++;await assert.rejects(runBatch({...args,manifestHash:'wrong'}),/MANIFEST_DRIFT/);await writeFile(join(args.root,'run.lock'),'crash fixture');await assert.rejects(runBatch(args),/EEXIST/);assert.equal(calls,0);await unlink(join(args.root,'journal.jsonl'));await assert.rejects(initialize(args.root,manifest),/EEXIST/);});
test('quotes/source/receipt binding, unchanged marker, and difference reconstruction',async()=>{const s=manifest.cases[0].source;const receipt={mode:'synthetic',model:MODEL,response_id:'resp_test',request_id:'req_test',input_tokens:500,output_tokens:100};const a=await candidateArtifact(s,output(s),receipt);assert.equal((await validateArtifact(a,s)).changed,false);await assert.rejects(validateArtifact(a,manifest.cases[1].source),/STALE/);assert.throws(()=>validateOutput({...output(s),citations:[{field:'intro_description',quote:'Invented guarantee'}]},s),/UNBOUND/);await assert.rejects(validateArtifact({...a,receipt:{...receipt,input_tokens:4001}},s),/RECEIPT/);const d=difference('Hello old world','Hello new world');assert.equal(d.prefix+d.removed+d.suffix,'Hello old world');assert.equal(d.prefix+d.added+d.suffix,'Hello new world');});
test('transport uses fixed endpoints, zero redirects and identical token-bearing fields',async t=>{const previous=globalThis.fetch;t.after(()=>globalThis.fetch=previous);const requests=[];globalThis.fetch=async(url,options)=>{requests.push({url,options});return new Response(JSON.stringify({object:'response.input_tokens',input_tokens:500}),{headers:{'x-request-id':'fixture'}});};const send=liveTransport(()=>'synthetic-not-a-key'),body=payload(manifest.cases[0].source);await send('count',body,'fixture-1');await send('generate',body,'fixture-2');assert.deepEqual(requests.map(r=>r.url),['https://api.openai.com/v1/responses/input_tokens','https://api.openai.com/v1/responses']);for(const r of requests)assert.equal(r.options.redirect,'error');const counted=JSON.parse(requests[0].options.body),generated=JSON.parse(requests[1].options.body);for(const k of Object.keys(counted))assert.deepEqual(counted[k],generated[k]);assert.equal(generated.max_output_tokens,1500);assert.equal(generated.service_tier,'default');await assert.rejects(send('other',body,'fixture'),/INVALID_REQUEST_KIND/);});
test('concurrent batch cannot dispatch while first holds lock',async t=>{const args=await fixture(t);let release,entered;const started=new Promise(r=>entered=r),pause=new Promise(r=>release=r);let calls=0;const first=runBatch({...args,transport:async()=>{calls++;entered();await pause;throw Error('fixture unknown');}});const stopped=assert.rejects(first,/UNKNOWN_STOP/);await started;await assert.rejects(runBatch({...args,transport:async()=>calls++}),/EEXIST/);release();await stopped;assert.equal(calls,1);});
for(const [name,mutate] of [['usage mismatch',b=>b.usage.input_tokens++],['truncated',b=>b.status='incomplete'],['unbound quote',b=>{const o=JSON.parse(b.output[0].content[0].text);o.citations[0].quote='invented';b.output[0].content[0].text=JSON.stringify(o);}],['wrong model',b=>b.model='other'],['unexpected tool',b=>b.output.push({type:'function_call'})]])test(name+' stops batch without artifact or replay',async t=>{const args=await fixture(t),calls=[],fake=transport(calls);args.transport=async(...v)=>{const reply=await fake(...v);if(v[0]==='generate')mutate(reply.body);return reply;};await assert.rejects(runBatch(args),/UNKNOWN_STOP/);await assert.rejects(readFile(join(args.root,'public-intro.candidate.json')),/ENOENT/);assert.equal((await readback(args.root)).calls,2);await assert.rejects(runBatch(args),/PRIOR_DISPATCH/);assert.equal(calls.length,2);});
test('SIGKILL after prewrite preserves slot, budget and crash lock',async t=>{const {spawn}=await import('node:child_process');const args=await fixture(t);const script=`import {runBatch} from ${JSON.stringify(new URL('./runner.mjs',import.meta.url).href)};await runBatch({...${JSON.stringify({...args,clock:undefined})},clock:()=>${APPROVED_AT+1000},transport:async()=>{process.stdout.write('RESERVED\\n');await new Promise(()=>{setInterval(()=>{},1000);});}});`;const child=spawn(process.execPath,['--input-type=module','-e',script],{stdio:['ignore','pipe','pipe']});t.after(()=>child.kill('SIGKILL'));await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('child timeout')),5000);child.stdout.once('data',()=>{clearTimeout(timer);resolve();});child.once('exit',code=>{clearTimeout(timer);reject(Error('early exit '+code));});});const exit=new Promise(resolve=>child.once('exit',(code,signal)=>resolve(signal)));child.kill('SIGKILL');assert.equal(await exit,'SIGKILL');const r=await readback(args.root);assert.equal(r.calls,1);assert.equal(r.reserved_nusd,100);assert.equal(r.state,'STOPPED_OR_UNKNOWN');await assert.rejects(runBatch({...args,transport:async()=>assert.fail('must not dispatch')}),/EEXIST/);});
