// Entirely runner-owned: native candidate Auth/SQL + actual WP/HTTP/gateway/source + original publisher.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {chromium} from 'playwright';
import {JSDOM} from 'jsdom';
import {createThemedSite} from './site-fixture.mjs';
import {wiringFixture,candidateBackend as backend} from '../wiring-fixture.mjs';
import {childHost,freeOrigin} from '../../wordpress-pilot/host-fixture-client.mjs';
import {createStore,openStore,restoreBackup} from '../../wordpress-pilot/store.mjs';
import {enterWorkspaceSession} from '../../owner-workspace/session-browser.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
export async function verifyUI({login,call,authOrigin,restOrigin,ids,snapshot,run,widths=[1280,390],recoveryHook=null}){
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined});const results=[];
 try{for(const width of widths){
  const dir=await mkdtemp('/tmp/'+run+'-theme-'),origin='http://127.0.0.1:8791';let site,host,gateway,context,page,session,posts=0,lose=true,savePosts=0,reviewPosts=0;const errors=[];
  try{
   site=await createThemedSite();const controls=site.controls(),before=JSON.parse(snapshot()),baseline=(await site.call(site.path(site.target))).json();const htmlBefore={};
   const native=async(url,o={})=>{const u=new URL(url);assert.equal(u.origin,backend);let target,path;if(u.pathname==='/auth/v1/user'){target=authOrigin;path='/user';}else if(u.pathname.startsWith('/rest/v1/')){target=restOrigin;path=u.pathname.slice(8)+u.search;}else throw Error('Native route denied');const r=await call(target,path,{method:o.method??'GET',token:new Headers(o.headers).get('authorization')?.slice(7),body:o.body?JSON.parse(o.body):undefined});return {status:r.status,ok:r.status>=200&&r.status<300,json:async()=>r.data};};
   const binding={organization_id:ids.org,page_id:site.target,pilot_id:site.run+'-'+width,target_url:site.targetURL},now=Date.now(),grant={pilot_id:binding.pilot_id,approval_reference:'isolated-theme-verification',starts_at:now-1,expires_at:now+300000};
   const config={enabled:true,gsc_measurement_enabled:true,evidence_environment:'isolated_fixture',binding,write_grant:grant,read_grant:{...grant,expires_at:now+360000},storage_directory:dir+'/store',authority:{origin:backend,key:'sb_publishable_isolated',redirectOrigin:origin}};createStore(config.storage_directory,binding);
   const hostOrigin=await freeOrigin(),wrapped={...site,call:async(path,o={})=>{if(o.method==='POST')posts++;const r=await gateway.siteCall(path,o);if(o.method==='POST'&&lose&&r.status===200){lose=false;throw Error('Lost committed theme reply');}return r;}};
   const start=async(c=config)=>childHost({config:c,site:wrapped,fetchImpl:native,...(c===config?{origin:hostOrigin}:{})});host=await start();gateway=await wiringFixture({site,database:dir+'/scanner.sqlite',publication_origin:hostOrigin});
   async function fresh(role='owner'){
    await context?.close();context=await browser.newContext({viewport:{width,height:844},serviceWorkers:'block'});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
    await context.route('**/*',async route=>{try{const req=route.request(),u=new URL(req.url());
     if(u.origin===origin)return route.fulfill(await gateway.route(req));
     if(u.origin==='https://rc-source.example'){const r=await gateway.siteCall(u.pathname+u.search,{authenticated:false});return route.fulfill({status:r.status,contentType:'text/html; charset=utf-8',body:r.text});}
     if(u.origin!==backend)throw Error('External request denied');
     if(req.method()==='POST'&&u.pathname.endsWith('/rpc/save_url_result_draft'))savePosts++;
     if(req.method()==='POST'&&u.pathname.endsWith('/rpc/review_url_result'))reviewPosts++;
     const r=await native(req.url(),{method:req.method(),headers:req.headers(),body:req.method()==='POST'?req.postData():undefined});return route.fulfill({status:r.status,contentType:'application/json',body:JSON.stringify(await r.json())});
    }catch(e){errors.push(e.message);return route.abort();}});
    const old=session?.access_token;session=await login(role);assert.notEqual(session.access_token,old);await enterWorkspaceSession(page,{origin,access_token:session.access_token,expires_in:session.expires_in});assert.deepEqual(await context.cookies(),[]);
   }
   async function logout(){await page.locator('#sign-out').click();assert.equal((await call(authOrigin,'/logout?scope=local',{method:'POST',token:session.access_token})).status,204);assert.equal((await call(authOrigin,'/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}})).status,400);}
   const open=async id=>{const v=page.locator(`.typed-version[data-version-id="${id}"]`);await v.locator('.typed-loader > summary').click();await v.locator('.typed-draft').waitFor();return v;};
   await fresh();
   for(const item of site.pack.pages){
    const response=await gateway.siteCall(item.path,{authenticated:false});assert.equal(response.status,200,item.path+' '+response.text.slice(0,100));htmlBefore[item.slug]=hash(response.text);const dom=new JSDOM(response.text),d=dom.window.document;
    assert.equal(d.title,item.title);assert.equal(d.querySelectorAll('meta[name="description"]').length,1);assert.equal(d.querySelector('meta[name="description"]').content,item.meta_description);assert.equal(d.querySelector('meta[name="growth-public-ready"]').content,'false');assert.equal(d.querySelectorAll('[itemtype="https://schema.org/Product"]').length,item.kind==='product'?1:0);assert.equal(d.querySelectorAll('[itemprop="description"]').length,item.kind==='product'?1:0);assert.equal(d.querySelectorAll('[itemprop="name"]').length,item.kind==='product'?1:0);assert.equal(d.querySelectorAll('form').length,0);if(item.kind==='product'){assert.equal(d.querySelector('[itemprop="name"]').textContent,'Growth OS');assert.equal(d.querySelector('[itemprop="description"]').textContent,item.description);assert.equal(d.querySelector('article').dataset.pageId,String(site.target));}else assert.equal(d.querySelector('meta[property="og:type"]'),null);dom.window.close();
    await page.goto('https://rc-source.example'+item.path);await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#main-content').evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok(await page.locator('nav a').first().evaluate(e=>e.getBoundingClientRect().height>=44));await page.locator('nav a').first().focus();assert.notEqual(await page.locator('nav a').first().evaluate(e=>getComputedStyle(e).outlineStyle),'none');await page.screenshot({path:'/tmp/'+run+'-theme-'+width+'-'+item.slug+'.png',fullPage:true});
   }
   await page.goto(origin+'/first-result.html');await page.locator('#source-url').fill(site.targetURL);await page.locator('#source-submit').focus();await page.keyboard.press('Enter');await page.locator('#review-title').waitFor();
   const texts={title:'Growth OS｜從網址開始確認內容改善',meta_description:'Growth OS 開發中：檢視有來源的內容改善建議、確認版本與受控發布；尚無真實流量改善結果。',description:site.pack.pages[0].description+' 目前仍在隔離驗證階段，尚未公開提供服務。'};
   for(const [key,value]of Object.entries(texts)){await page.locator('#review-'+key).fill(value);await page.locator('#review-check-'+key).check();}await page.locator('#review-confirm').click();const download=page.waitForEvent('download');await page.locator('#export-result').click();const payload=JSON.parse(await readFile(await(await download).path(),'utf8'));assert.equal(payload.facts.product_name.value,'Growth OS');assert.equal(payload.snapshot.original_url,site.targetURL);
   await fresh();await page.getByLabel('匯入成果與來源 JSON').setInputFiles({name:'theme-result.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await page.locator('#url-save-preview .typed-draft').waitFor();await page.locator('#save-url-result').focus();await page.keyboard.press('Enter');await page.locator('#url-save-feedback').filter({hasText:'已保存第 1 版'}).waitFor();assert.equal(savePosts,1);
   const saved=JSON.parse(snapshot()).versions.find(v=>!before.versions.some(b=>b.id===v.id));assert.deepEqual(saved.first_result_payload,payload);
   await logout();await fresh();let view=await open(saved.id);assert.deepEqual(JSON.parse(await view.locator('.typed-draft > details').last().locator('pre').textContent()).payload,payload);
   await page.waitForFunction(id=>{const e=document.querySelector(`.typed-version[data-version-id="${id}"] [data-review-check="title"]`);return e&&!e.disabled;},saved.id);
   for(const key of ['title','meta_description','description','source','blocking_facts_clear']){await view.locator(`[data-review-check="${key}"]`).focus();await page.keyboard.press('Space');}await view.locator('.url-review-confirm').focus();await page.keyboard.press('Enter');await view.locator('.url-review-status').filter({hasText:'此已保存版本已確認'}).waitFor();assert.equal(reviewPosts,1);
   const reviewed=JSON.parse(snapshot());assert.equal(reviewed.versions.length,before.versions.length+1);assert.equal(reviewed.reviews.length,before.reviews.length+1);assert.equal(reviewed.audit.length,before.audit.length+2);
   const panel=()=>view.locator('.wordpress-publication'),status=text=>panel().locator('.wp-status').filter({hasText:text}).waitFor();await panel().locator('.wp-preview').focus();await page.keyboard.press('Enter');await status('尚未發布；請核對');await panel().locator('.wp-confirm').focus();await page.keyboard.press('Space');await panel().locator('.wp-publish').focus();await page.keyboard.press('Enter');await status('提交結果未知');assert.equal(posts,1);
   const unknown=(await host.dispatch(session.access_token,'history',{version_id:saved.id})).at(-1);assert.equal(unknown.state,'unknown');const oldPid=host.pid;await host.close();if(recoveryHook)await recoveryHook.assertUnsettled({dir,binding});host=await start();assert.notEqual(host.pid,oldPid);await logout();await fresh();view=await open(saved.id);await panel().locator('.wp-history').click();await status('提交結果未知');await panel().locator('.wp-readback').click();await status('已發布並由 API');assert.equal(posts,1);
   const published=(await site.call(site.path(site.target))).json();assert.equal(published.title.raw,texts.title);assert.equal(published.meta.growth_meta_description,texts.meta_description);assert.deepEqual(site.controls(),controls);
   for(const slug of ['about','privacy'])assert.equal(hash((await gateway.siteCall('/'+slug+'/',{authenticated:false})).text),htmlBefore[slug]);
   lose=true;await panel().locator('.wp-restore-confirm').focus();await page.keyboard.press('Space');await panel().locator('.wp-restore').focus();await page.keyboard.press('Enter');await status('恢復結果未知');assert.equal(posts,2);await panel().locator('.wp-readback').click();await status('已恢復發布前內容');assert.equal(posts,2);const restored=(await site.call(site.path(site.target))).json();for(const key of ['title','content','meta'])assert.deepEqual(restored[key],baseline[key]);assert.deepEqual(site.controls(),controls);await view.locator('.measurement-read').click();await view.locator('.measurement-status').filter({hasText:'量測已讀回'}).waitFor();assert.match(await view.locator('.measure-baseline-result').innerText(),/未知（不是零）/);assert.match(await view.locator('.measure-followup-result').innerText(),/未知（不是零）/);await panel().screenshot({path:'/tmp/'+run+'-theme-'+width+'-restored.png'});
   for(const id of [site.pages.about,site.pages.privacy])assert.equal((await site.call(site.path(id),{method:'POST',headers:{'x-growth-before':restored.growth_revision},body:{title:'denied',content:'denied',meta:{growth_meta_description:'denied'}}})).status,403);assert.equal(site.attempts(),2);assert.deepEqual(site.controls(),controls);
   const history=await host.dispatch(session.access_token,'history',{version_id:saved.id});if(recoveryHook){results.push(await recoveryHook.restore({width,dir,site,host,gateway,context,session,config,binding,saved,payload,history,controls,htmlBefore,posts,run,logout,browser}));continue;}await host.close();const store=openStore(config.storage_directory,binding),archive=dir+'/journal-backup.json';let backup;try{backup=store.backup(archive);}finally{store.close();}const recovery=restoreBackup(archive,dir+'/recovered',binding);assert.equal(recovery.mode,'readonly');host=await start();await logout();await fresh();view=await open(saved.id);assert.deepEqual(await host.dispatch(session.access_token,'history',{version_id:saved.id}),history);
   const recovered=await start({...config,storage_directory:dir+'/recovered'});try{assert.deepEqual(await recovered.dispatch(session.access_token,'history',{version_id:saved.id}),history);await assert.rejects(recovered.dispatch(session.access_token,'publish',{version_id:saved.id,intent_id:unknown.id,page_id:site.target,confirm:true}));}finally{await recovered.close();}
   const v2=await call(restOrigin,'/rpc/save_url_result_draft',{method:'POST',token:session.access_token,body:{p_organization_id:ids.org,p_opportunity_id:saved.opportunity_id,p_request_id:randomUUID(),p_expected_version:1,p_payload:payload}});assert.equal(v2.status,200);await logout();await fresh();view=await open(saved.id);assert.deepEqual(await host.dispatch(session.access_token,'history',{version_id:saved.id}),history);await assert.rejects(host.dispatch(session.access_token,'preview',{version_id:saved.id}));assert.equal(posts,2);
   await logout();await fresh('viewer');view=await open(saved.id);const state=snapshot();await assert.rejects(host.dispatch(session.access_token,'history',{version_id:saved.id}));assert.equal(snapshot(),state);assert.deepEqual(site.controls(),controls);assert.deepEqual(errors,[]);
   const proof={width,theme_pages:3,product_scopes:1,control_product_scopes:0,keyboard_skip_navigation_save_review_publish_restore:true,public_ready:false,native_save_review:true,native_logout_fresh_readback:true,wordpress_posts:posts,unknown_get_only:true,controls_html_and_sql_unchanged:true,exact_restore:true,restarted_history_exact:true,old_version_history_retained:true,journal_backup_readonly_recovery:true,backup,full_multi_store_restore:'NOT RUN: separate next slice',scanner:'real owned WordPress HTML through unchanged Python HTTP scanner',gateway:gateway.proof(),no_horizontal_overflow:true};results.push(proof);
  }catch(e){if(recoveryHook&&page&&!page.isClosed()){await page.screenshot({path:'/tmp/'+run+'-failure.png',fullPage:true});await writeFile('/tmp/'+run+'-failure.html',await page.content(),{mode:0o600});}throw e;}finally{await context?.close();await gateway?.close();await host?.close();await site?.close();await rm(dir,{recursive:true,force:true});}
 }}finally{await browser.close();}
 await writeFile('/tmp/'+run+'-theme-ui.json',JSON.stringify(results,null,2)+'\n',{mode:0o600});return results;
}
