// Synthetic local-only UI acceptance, including a real narrow mobile viewport.
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {readFile} from 'node:fs/promises';
const origin='http://127.0.0.1:8765';
const server=spawn('python3',['-m','http.server','8765','--bind','127.0.0.1','--directory','apps/web'],{stdio:'ignore'});
let browser;
try {
  let ready=false;
  for(let i=0;i<50;i++) {try {const response=await fetch(origin+'/search-baseline.html'); if(response.ok){ready=true;break;}} catch {} await new Promise(resolve=>setTimeout(resolve,100));}
  assert.ok(ready,'local static server must start');
  browser=await chromium.launch();
  for(const width of [1280,390]) {
    const page=await browser.newPage({viewport:{width,height:844}}), errors=[];
    page.on('pageerror',error=>errors.push(error.message));
    page.on('console',message=>{if(message.type()==='error') errors.push(message.text());});
    await page.goto(origin+'/');
    await page.locator('#status a[href="/search-baseline.html"]').click();
    await page.locator('[data-sample="a"]').click();
    assert.match(await page.locator('#result-a').innerText(),/日期完整：3 \/ 3 天/);
    await page.locator('#second>summary').click();
    await page.locator('[data-sample="b"]').click(); await page.locator('#compare').click();
    assert.match(await page.locator('#comparison').innerText(),/點擊 \+2 · 曝光 \+10/);
    await page.locator('#action-form input[name=date]').fill('2026-09-04');
    await page.locator('#action-form input[name=path]').fill('/../private');
    await page.locator('#action-form input[name=note]').fill('更新商品比較內容');
    await page.locator('#action-form button[type=submit]').click();
    assert.match(await page.locator('#action-error').innerText(),/頁面路徑/);
    await page.locator('#action-form input[name=path]').fill('/product-comparison');
    await page.locator('#action-form button[type=submit]').click();
    assert.match(await page.locator('#action-list').innerText(),/更新商品比較內容/);
    await page.locator('#build-report').click();
    assert.match(await page.locator('#report-result').innerText(),/合成範例/);
    assert.match(await page.locator('.report-summary').innerText(),/可比較觀察值，不能歸因/);
    assert.match(await page.locator('.report-summary').innerText(),/不是真實成長證據/);
    const reportDownloadPromise=page.waitForEvent('download'); await page.locator('#download-report').click();
    const reportDownload=await reportDownloadPromise; const reportText=await readFile(await reportDownload.path(),'utf8');
    for(const heading of ['觀測','合理推論','未知','建議動作']) assert.ok(reportText.includes('## '+heading));
    assert.ok(reportText.includes('## 先看這裡')); assert.match(reportText,/優先下一步/);
    assert.match(reportText,/點擊差額 \+2/);
    assert.match(reportText,/更新商品比較內容/); assert.match(reportText,/後續期間/);
    const downloadPromise=page.waitForEvent('download'); await page.locator('#save-snapshot').click();
    const download=await downloadPromise; const saved=await readFile(await download.path());
    await page.reload(); assert.equal(await page.locator('#save-snapshot').isDisabled(),true);
    await page.locator('#snapshot-file').setInputFiles({name:'baseline.json',mimeType:'application/json',buffer:saved});
    await page.locator('#result-b').waitFor({state:'visible'});
    assert.match(await page.locator('#snapshot-feedback').innerText(),/已重新驗證並載入/);
    await page.locator('#compare').click(); assert.match(await page.locator('#comparison').innerText(),/點擊 \+2 · 曝光 \+10/);
    assert.match(await page.locator('#action-list').innerText(),/更新商品比較內容/);
    await page.locator('#build-report').click();
    await page.locator('#action-list button').click();
    assert.equal(await page.locator('#report-result').isVisible(),false);
    assert.equal(await page.locator('#download-report').isDisabled(),true);
    await page.locator('#build-report').click();
    assert.match(await page.locator('#report-result').innerText(),/尚未提供發布紀錄/);
    const malformed=JSON.parse(saved); malformed.a.rows[0].clicks=-1;
    await page.locator('#snapshot-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(malformed))});
    await page.waitForFunction(()=>document.getElementById('snapshot-feedback').textContent.includes('無效'));
    assert.equal(await page.locator('#result-a').isVisible(),false);
    assert.equal(await page.locator('#save-snapshot').isDisabled(),true);
    await page.locator('[data-sample="a"]').click(); await page.locator('[data-sample="b"]').click();

    await page.locator('#form-a textarea').fill('date,clicks,impressions\n2026-09-01,2,10\n2026-09-03,0,0');
    assert.equal(await page.locator('#result-a').isVisible(),false); assert.equal(await page.locator('#compare').isDisabled(),true);
    assert.equal(await page.locator('#report-result').isVisible(),false); assert.equal(await page.locator('#download-report').isDisabled(),true);
    await page.locator('#form-a button[type=submit]').click();
    assert.match(await page.locator('#result-a').innerText(),/未知日期：2026-09-02/);
    await page.locator('#build-report').click(); assert.match(await page.locator('#report-result').innerText(),/本次未產生期間差額/);
    assert.match(await page.locator('.report-summary').innerText(),/先補齊基線資料/);
    assert.match(await page.locator('.report-summary').innerText(),/才填零/);
    await page.locator('#compare').click(); assert.match(await page.locator('#comparison-error').innerText(),/兩段期間都須沒有缺少日期/);
    await page.locator('#form-a textarea').fill('date,clicks,impressions\n2026-09-01,,10'); await page.locator('#form-a button[type=submit]').click();
    assert.match(await page.locator('#error-a').innerText(),/第 2 行/);
    await page.locator('#form-a input[type=file]').setInputFiles('apps/web/search-baseline-template.csv');
    await page.waitForFunction(()=>document.querySelector('#form-a textarea').value.includes('2026-09-03,1,10'));
    await page.locator('#form-a button[type=submit]').click(); assert.match(await page.locator('#result-a').innerText(),/日期完整：3 \/ 3 天/);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow');
    assert.deepEqual(errors,[],'no page or console errors');
    await page.close(); console.log(`PASS: ${width}px preview, comparison, invalidation, coverage, errors, CSV selection, navigation, overflow`);
  }
} finally {if(browser) await browser.close(); server.kill();}
