// Offline materialization only. No remote, served-file write or implicit clock.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {frozen} from '../../url_result/bound/generate.mjs';
import {canonical,validateReport} from '../../../../apps/web/first-result-payload.mjs';
export const root=new URL('./',import.meta.url),cutoffToken='__OWNER_APPROVED_UTC_CUTOFF__';
export const requestId='1f3f43cb-a64c-4739-a4a7-772d5b2cb781',versionId='5802e838-8a06-46c6-934a-0a8c38ba1daa';
export const sha=v=>createHash('sha256').update(v).digest('hex'),quote=v=>"'"+v.replaceAll("'","''")+"'";
export const checks={title:true,meta_description:true,description:true,source:true,blocking_facts_clear:true};
export const signature='(uuid,uuid,uuid,text,text,text,jsonb)',entries=['public.review_url_result','private.review_url_result_impl'].map(f=>f+signature);
const saveEntries=['public.save_url_result_draft','private.save_url_result_draft_impl'].map(f=>f+'(uuid,uuid,uuid,integer,jsonb)');
export function aclClosed(functions){return `if exists(select 1 from pg_proc p cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.oid in (${functions.map(f=>quote(f)+'::regprocedure').join(',')}) and a.grantee=0 and a.privilege_type='EXECUTE') or exists(select 1 from (values('anon'),('authenticated'),('service_role')) acl_role(name) cross join (values${functions.map(f=>'('+quote(f)+'::regprocedure)').join(',')}) f(id) where has_function_privilege(acl_role.name,f.id,'EXECUTE')) then raise exception 'Expected closed effective ACL'; end if;`;}
export async function source(){
 const base=new URL('../../url_result/revision-bound/owner-candidate-20261004T060000Z/',root);
 const hashes=JSON.parse(await readFile(new URL('hashes.json',base),'utf8'));for(const [file,hash]of Object.entries(hashes))if(sha(await readFile(new URL(file,base)))!==hash)throw Error('Accepted artifact drift: '+file);
 const prior=JSON.parse(await readFile(new URL('manifest.json',base),'utf8')),payload=JSON.parse(await readFile(new URL('v2-payload.json',base),'utf8'));await validateReport(payload);
 const old=await frozen(),opening=await readFile(new URL('opening.sql',base),'utf8');
 const impl=opening.slice(opening.indexOf('create or replace function private.save_url_result_draft_impl('),opening.indexOf('\n$revision_ddl$'));
 const saveBody=impl.slice(impl.indexOf('as $$')+5,impl.lastIndexOf('$$;'));
 return {prior,payload,v1:old.payload,saveBody};
}
export async function manifest(){
 const {prior:p,payload,saveBody}=await source();
 const body={p_organization_id:p.organization_id,p_version_id:versionId,p_request_id:requestId,p_source_digest:p.source_digest,p_content_digest:p.content_digest,p_version_digest:p.request_digest,p_checks:checks};
 return {schema_version:1,state:'UNAPPROVED_OFFLINE_CANDIDATE',kind:'exact_version_review',project_ref:p.project_ref,actor_id:p.actor_id,organization_id:p.organization_id,opportunity_id:p.opportunity_id,version_id:versionId,version_number:2,save_request_id:p.request_id,version_digest:p.request_digest,source_digest:p.source_digest,content_digest:p.content_digest,payload_canonical_sha256:sha(canonical(payload)),v1_id:p.base_version_id,v1_version_digest:p.base_request_digest,v1_payload_canonical_sha256:p.base_payload_canonical_sha256,request_id:requestId,checks,intent_digest:'sha256:'+sha(canonical(body)),expected_save_prosrc_sha256:sha(saveBody),proposal_sha256:sha(await readFile(new URL('../proposal.sql',root))),cutoff:null,workspace_url:p.workspace_url,opening_migration_name:'url_review_bound_open_v2',cleanup_migration_name:'url_review_bound_close_v2',expected_history_before:23,budget:{tracked_migrations:2,config_transitions:2,login_requests:2,review_post_attempts:1,save_post_attempts:0,parent_inserts:0,version_inserts:0,review_inserts:1,audit_inserts:1},result_state:'draft',published:false};
}
export async function render(m,{cutoff=cutoffToken}={}){
 if(cutoff!==cutoffToken&&(!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(cutoff)||!Number.isFinite(Date.parse(cutoff))||new Date(cutoff).toISOString()!==cutoff))throw Error('Explicit canonical UTC cutoff required');
 const expected=await manifest();if(canonical({...m,cutoff:null,state:expected.state})!==canonical(expected))throw Error('Exact candidate manifest required');
 const {payload,v1}=await source(),proposal=await readFile(new URL('../proposal.sql',root),'utf8');
 const deadline=`if clock_timestamp()>=${quote(cutoff)}::timestamptz then raise exception 'Bound Review expired' using errcode='42501'; end if;`;
 const fixed=`${deadline}\n if actor is distinct from '${m.actor_id}'::uuid or p_organization_id is distinct from '${m.organization_id}'::uuid or p_version_id is distinct from '${m.version_id}'::uuid or p_request_id is distinct from '${m.request_id}'::uuid or p_source_digest is distinct from '${m.source_digest}' or p_content_digest is distinct from '${m.content_digest}' or p_version_digest is distinct from '${m.version_digest}' or p_checks is distinct from ${quote(JSON.stringify(checks))}::jsonb then raise exception 'Fixed Review scope required' using errcode='42501'; end if;`;
 const exactRow=(id,n,p,digest,req)=>`exists(select 1 from public.content_versions where id='${id}' and organization_id='${m.organization_id}' and opportunity_id='${m.opportunity_id}' and created_by='${m.actor_id}' and version_number=${n} and status='draft' and first_result_expected_version=${n-1} and first_result_request_id='${req}' and first_result_request_digest='${digest}' and first_result_payload=${quote(JSON.stringify(p))}::jsonb and first_result_request_digest=private.fr_request_digest(organization_id,opportunity_id,created_by,first_result_request_id,first_result_expected_version,first_result_payload) and title=first_result_payload#>>'{preview,fields,title,suggested}' and draft_body=first_result_payload#>>'{preview,fields,description,suggested}')`;
 const {prior}=await source();
 const exactVersions=`if not ${exactRow(m.v1_id,1,v1,m.v1_version_digest,prior.base_request_id)} or not ${exactRow(m.version_id,2,payload,m.version_digest,m.save_request_id)} or (select count(*) from public.content_versions where organization_id='${m.organization_id}' and opportunity_id='${m.opportunity_id}')<>2 then raise exception 'Exact existing v1/v2 required'; end if;\n if not exists(select 1 from public.growth_opportunities where id='${m.opportunity_id}' and organization_id='${m.organization_id}' and entry_kind='url_result' and status='url_pending_review' and source_identity=private.url_source_identity(${quote(JSON.stringify(payload))}::jsonb)) then raise exception 'Exact URL parent required'; end if;`;
 const preflight=`if (select count(*) from supabase_migrations.schema_migrations)<>23 then raise exception 'Expected 23 history records'; end if;\n ${aclClosed(saveEntries)}\n if (select encode(sha256(convert_to(prosrc,'UTF8')),'hex') from pg_proc where oid='${saveEntries[1]}'::regprocedure) is distinct from '${m.expected_save_prosrc_sha256}' then raise exception 'Existing Save implementation drift'; end if;\n ${exactVersions}\n if to_regprocedure('${entries[0]}') is not null or to_regprocedure('${entries[1]}') is not null or exists(select 1 from information_schema.columns where table_schema='public' and table_name='content_reviews' and column_name like 'url_review_%') then raise exception 'Review candidate already installed or schema drift'; end if;\n if exists(select 1 from public.content_reviews where version_id='${m.version_id}') or exists(select 1 from public.audit_events where details->>'request_id'='${m.request_id}') then raise exception 'Review must be unused'; end if;\n if not exists(select 1 from public.organization_members where organization_id='${m.organization_id}' and user_id='${m.actor_id}' and role='owner') then raise exception 'Owner membership missing'; end if;`;
 let bounded=proposal;
 const once=(a,b)=>{if(bounded.split(a).length!==2)throw Error('Unexpected accepted proposal anchor');bounded=bounded.replace(a,()=>b);};
 once('begin\n if actor','begin\n '+fixed+'\n if actor');
 for(const anchor of ["perform 1 from public.organizations where id=p_organization_id for no key update;","if not found then raise exception 'Owner membership changed' using errcode='42501'; end if;","if not found or v.status<>'draft' or v.first_result_payload is null then raise exception 'Typed draft required' using errcode='23514'; end if;"])once(anchor,anchor+'\n '+deadline);
 once(' perform private.fr_require(private.fr_valid_payload',` if v.opportunity_id is distinct from '${m.opportunity_id}'::uuid or v.created_by is distinct from '${m.actor_id}'::uuid or v.version_number<>2 or v.first_result_request_id is distinct from '${m.save_request_id}'::uuid or v.first_result_payload is distinct from ${quote(JSON.stringify(payload))}::jsonb or v.first_result_request_digest is distinct from private.fr_request_digest(v.organization_id,v.opportunity_id,v.created_by,v.first_result_request_id,v.first_result_expected_version,v.first_result_payload) then raise exception 'Fixed stored v2 required' using errcode='42501'; end if;\n perform private.fr_require(private.fr_valid_payload`);
 once('  return prior.id;',`  ${deadline}\n  return prior.id;`);once(' insert into public.content_reviews(',` ${deadline}\n insert into public.content_reviews(`);once(' return result_id;',` ${deadline}\n return result_id;`);
 const opening=`-- UNAPPROVED OFFLINE CANDIDATE. One new tracked migration; no Save grants or historical replay.\nDO $review_open$ BEGIN\n ${preflight}\n ${deadline}\n EXECUTE $review_ddl$\n${bounded}\ngrant execute on function ${entries.join(',')} to authenticated;\n$review_ddl$;\nEND $review_open$;\n`;
 const cleanup=`-- Separate tracked cleanup; retain new schema, bounded body and successful review/audit.\nDO $review_close$ BEGIN\n revoke all on function ${entries.join(',')} from public,anon,authenticated,service_role;\n ${aclClosed(entries)}\nEND $review_close$;\n`;
 const configText=enabled=>'// OFFLINE TEMPLATE ONLY. No authorization; bind cutoff and verify frozen hashes first.\nexport const urlResultSchemaEnabled=true;\nexport const urlSaveEnabled=false;\nexport const urlSaveTrial=null;\nexport const urlReviewEnabled=false;\nexport const urlReviewSchemaEnabled=true;\nexport const urlReviewTrial=Object.freeze('+JSON.stringify({...m,enabled,expires_at:cutoff===cutoffToken?null:cutoff},null,2)+');\n';
 const postflight=`-- Read-only success assertions AFTER cleanup. Unknown/zero uses preservation + original-request SELECT, not retries.\nDO $review_post$ DECLARE r public.content_reviews%rowtype; BEGIN\n if (select count(*) from supabase_migrations.schema_migrations)<>25 then raise exception 'Expected 25 history records'; end if;\n ${aclClosed(saveEntries.concat(entries))}\n ${exactVersions}\n select * into strict r from public.content_reviews where organization_id='${m.organization_id}' and url_review_request_id='${m.request_id}';\n if r.actor_user_id is distinct from '${m.actor_id}'::uuid or r.version_id is distinct from '${m.version_id}'::uuid or r.decision<>'approved' or r.url_review_source_digest is distinct from '${m.source_digest}' or r.url_review_content_digest is distinct from '${m.content_digest}' or r.url_review_version_digest is distinct from '${m.version_digest}' or r.url_review_checks is distinct from ${quote(JSON.stringify(checks))}::jsonb then raise exception 'Fixed Review mismatch'; end if;\n if (select count(*) from public.audit_events where details->>'request_id'='${m.request_id}')<>1 then raise exception 'Expected exactly one new audit'; end if;\n if (select count(*) from public.audit_events where event_type='url_result_reviewed' and organization_id=r.organization_id and actor_user_id=r.actor_user_id and object_type='content_version' and object_id=r.version_id and details=jsonb_build_object('review_id',r.id,'request_id',r.url_review_request_id,'version_number',2,'source_digest',r.url_review_source_digest,'content_digest',r.url_review_content_digest,'version_digest',r.url_review_version_digest,'published',false))<>1 then raise exception 'Expected exact one review audit'; end if;\nEND $review_post$;\n`;
 const readback=`-- GET-equivalent read only: compare known review UUID when one was returned. Empty never permits POST.\nselect * from public.content_reviews where organization_id='${m.organization_id}' and version_id='${m.version_id}' and url_review_request_id='${m.request_id}';\nselect * from public.audit_events where organization_id='${m.organization_id}' and event_type='url_result_reviewed' and object_id='${m.version_id}' and details->>'request_id'='${m.request_id}';\nselect * from public.content_versions where organization_id='${m.organization_id}' and opportunity_id='${m.opportunity_id}' order by version_number;\n`;
 const start=bounded.indexOf('create function private.review_url_result_impl('),end=bounded.indexOf('create function public.review_url_result(');
 const implementation=bounded.slice(start,end).replace('create function private.','create or replace function private.');
 const expectedBody=implementation.slice(implementation.indexOf('as $$')+5,implementation.lastIndexOf('$$;'));
 const state=`-- READ ONLY authoritative DDL/DCL reconciliation. Compare with bound artifacts, not transport outcome.\nselect count(*) as history_count from supabase_migrations.schema_migrations;\nselect version,name,statements from supabase_migrations.schema_migrations where name in ('${m.opening_migration_name}','${m.cleanup_migration_name}') order by version;\nselect p.oid::regprocedure::text signature,p.prosecdef,p.proconfig,p.proowner,p.proacl::text,encode(sha256(convert_to(p.prosrc,'UTF8')),'hex') prosrc_sha256,case when p.proname='review_url_result_impl' then '${sha(expectedBody)}' end expected_bound_prosrc_sha256 from pg_proc p where p.oid in (${entries.map(f=>'to_regprocedure('+quote(f)+')').join(',')});\nselect acl_role.name as role,f.signature,has_function_privilege(acl_role.name,to_regprocedure(f.signature),'execute') as effective_execute from (values('anon'),('authenticated'),('service_role')) acl_role(name) cross join (values${saveEntries.concat(entries).map(f=>'('+quote(f)+')').join(',')}) f(signature);\nselect p.oid::regprocedure::text signature,a.* from pg_proc p cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.oid in (${saveEntries.concat(entries).map(f=>'to_regprocedure('+quote(f)+')').join(',')});\nselect column_name,data_type,is_nullable,column_default from information_schema.columns where table_schema='public' and table_name='content_reviews' and column_name like 'url_review_%' order by column_name;\nselect conname,pg_get_constraintdef(oid) definition from pg_constraint where conrelid='public.content_reviews'::regclass order by conname;\n`;
 return {opening,cleanup,preflight:'DO $review_pre$ BEGIN\n'+preflight+'\nEND $review_pre$;\n',postflight,readback,state,implementation,openConfig:configText(true),closedConfig:configText(false)};
}
export const artifactNames=['manifest.json','opening.sql.template','cleanup.sql','preflight.sql','postflight.sql','readback.sql','state.sql','preservation.sql','preview-open-config.mjs','preview-closed-config.mjs'];
if(process.argv[1]&&pathToFileURL(resolve(process.argv[1])).href===import.meta.url){
 const m=await manifest(),p=await render(m);
 for(const [file,bytes]of [['manifest.json',JSON.stringify(m,null,2)+'\n'],['opening.sql.template',p.opening],['cleanup.sql',p.cleanup],['preflight.sql',p.preflight],['postflight.sql',p.postflight],['readback.sql',p.readback],['state.sql',p.state],['preview-open-config.mjs',p.openConfig],['preview-closed-config.mjs',p.closedConfig]])await writeFile(new URL(file,root),bytes);
 const hashes={};for(const file of artifactNames)hashes[file]=sha(await readFile(new URL(file,root)));await writeFile(new URL('hashes.json',root),JSON.stringify(hashes,null,2)+'\n');console.log('Materialized null-cutoff candidate '+m.request_id);
}
