// Synthetic reconstruction ONLY. Historical openings never belong to the new remote package.
import {readFile} from 'node:fs/promises';
import {revisionBaseline} from '../../url_result/revision-bound/fixture.mjs';
import {source,manifest,quote,root} from './candidate.mjs';
export async function baseline({pglite=false}={}){
 const {prior,payload}=await source(),m=await manifest(),old=new URL('../../url_result/revision-bound/owner-candidate-20261004T060000Z/',root);
 const open=await readFile(new URL('opening.sql',old),'utf8'),close=await readFile(new URL('cleanup.sql',old),'utf8');
 const impl=open.slice(open.indexOf('create or replace function private.save_url_result_draft_impl('),open.indexOf('\n$revision_ddl$'));
 return await revisionBaseline({pglite})+open.replaceAll('2026-10-04T06:00:00.000Z','2099-01-01T00:00:00.000Z')+`set role authenticated;select set_config('request.jwt.claim.sub','${m.actor_id}',false);select public.save_url_result_draft('${m.organization_id}','${m.opportunity_id}','${prior.request_id}',1,${quote(JSON.stringify(payload))}::jsonb);reset role;update public.audit_events set object_id='${m.version_id}' where object_id=(select id from public.content_versions where first_result_request_id='${prior.request_id}');update public.content_versions set id='${m.version_id}' where first_result_request_id='${prior.request_id}';`+impl+close+`insert into supabase_migrations.schema_migrations values('20261004042328','url_revision_bound_open_v2',array[${quote(open)}]),('20261004050737','url_revision_bound_close_v2',array[${quote(close)}]);`;
}
export async function preservationSQL(db){
 const m=await manifest(),tables=(await db.query("select tablename from pg_tables where schemaname='public' order by tablename")).rows.map(r=>r.tablename);
 const columns=['url_review_request_id','url_review_source_digest','url_review_content_digest','url_review_version_digest','url_review_checks'];
 const statements=tables.map(table=>{
  if(!/^[a-z_]+$/.test(table))throw Error('Unexpected table');
  let projection='to_jsonb(t)',filter='';
  if(table==='content_reviews'){projection+='-array['+columns.map(quote).join(',')+']';filter=` where not (to_jsonb(t)->>'url_review_request_id' is not distinct from '${m.request_id}' and organization_id='${m.organization_id}' and version_id='${m.version_id}')`;}
  if(table==='audit_events')filter=` where not (event_type='url_result_reviewed' and organization_id='${m.organization_id}' and actor_user_id='${m.actor_id}' and object_id='${m.version_id}' and details->>'request_id' is not distinct from '${m.request_id}')`;
  return `select '${table}' as relation,count(*) as count,encode(sha256(convert_to(coalesce(jsonb_agg(${projection} order by ${projection}::text)::text,'[]'),'UTF8')),'hex') as sha256 from public.${table} t${filter}`;
 });
 const history=`select 'migration_history',count(*),encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(t) order by version)::text,'[]'),'UTF8')),'hex') from supabase_migrations.schema_migrations t where name not in ('${m.opening_migration_name}','${m.cleanup_migration_name}')`;
 return '-- READ ONLY. Capture before opening and compare after cleanup. New review columns excluded only from original-row projection.\n'+statements.concat(history).join('\nunion all\n')+' order by relation;\n'+
 `-- Catalog allowlist: only five columns/two constraints/unique index and two bounded functions may be added. Existing metadata must match.\nselect jsonb_build_object('tables',(select jsonb_agg(to_jsonb(x) order by relname) from (select c.relname,c.relowner,c.relrowsecurity,c.relforcerowsecurity,c.relacl::text from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r')x),'policies',(select jsonb_agg(to_jsonb(x) order by schemaname,tablename,policyname) from pg_policies x),'functions',(select jsonb_agg(to_jsonb(x) order by signature) from (select p.oid::regprocedure::text signature,p.proowner,p.proacl::text,p.proconfig,pg_get_functiondef(p.oid) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prokind='f' and p.proname not in ('review_url_result','review_url_result_impl'))x),'columns',(select jsonb_agg(to_jsonb(x) order by table_name,ordinal_position) from information_schema.columns x where table_schema='public' and not(table_name='content_reviews' and column_name in (${columns.map(quote).join(',')}))),'constraints',(select jsonb_agg(to_jsonb(x) order by relation,name) from (select conrelid::regclass::text relation,conname name,pg_get_constraintdef(oid) definition from pg_constraint where connamespace='public'::regnamespace and conname not in ('content_reviews_url_request_unique','content_reviews_url_shape'))x),'defaults',(select jsonb_agg(to_jsonb(x) order by oid) from pg_default_acl x),'roles',(select jsonb_agg(to_jsonb(x) order by rolname) from (select rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolbypassrls from pg_roles)x)) as unchanged_catalog;\n`;
}
