import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,chmodSync,existsSync,cpSync,rmSync} from 'node:fs';
import {readFile,writeFile,rm} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {nativeFixture} from './native-fixture.mjs';
import {wpRecovery} from './wp-fixture.mjs';
import {pack,verify,newTarget,sqliteSnapshot,settledJournal,writePrivate,sha,names} from './archive.mjs';
import {createThemedSite} from '../theme/site-fixture.mjs';
import {wiringFixture,candidateBackend as backend} from '../wiring-fixture.mjs';
import {openStore,restoreBackup} from '../../wordpress-pilot/store.mjs';
import {childHost} from '../../wordpress-pilot/host-fixture-client.mjs';
import {enterWorkspaceSession} from '../../owner-workspace/session-browser.mjs';
import {checkCatalog} from '../schema/native-checks.mjs';
export function recoveryChecks(source){return {
 async assertUnsettled({dir,binding}){assert.throws(()=>settledJournal(dir+'/store/journal.json',binding),/Unsettled/);},
 async restore({width,dir,site,host,gateway,context,session,config,binding,saved,payload,history,controls,htmlBefore,posts,run,logout,browser}){
  let targetSite,targetNative,targetHost,targetGateway,targetContext;const adapter=wpRecovery(site),target=dir+'/fresh-target';
  try{
   adapter.seedUpload();const exactPages=adapter.snapshot();await logout();await context.close();await gateway.close();await host.close();assert.equal(host.child.exitCode,0);const q=gateway.quiescence();assert.equal(q.gateway_closed&&q.scanner_exited,true);
   const operations=settledJournal(dir+'/store/journal.json',binding);assert.ok(operations.some(o=>o.state==='restored'&&o.version===saved.id));
   // Revoke old short-lived WP credentials before the stopped-writing checkpoint.
   await site.revoke();await site.expire();assert.ok([401,403].includes((await site.call(site.path(site.target))).status));
   const nativeQuiescence=await source.quiesce();adapter.pause();
   const checkpoint={id:randomUUID(),cut_at:new Date().toISOString(),binding,version_id:saved.id,page_ids:site.pages,operations,quiescence:{all_writers_stopped:true,wordpress_apache_processes_stopped:true,source_wordpress:site.run,wordpress:adapter.quiescence(),publisher_exited:true,...q,...nativeQuiescence}};
   const wp=adapter.capture();chmodSync(dir+'/scanner.sqlite',0o600);const sqlite=sqliteSnapshot(dir+'/scanner.sqlite',dir+'/scanner-backup.sqlite');
   assert.equal(sqlite.data.rows.public_source_snapshots.length,1);const snapshot=JSON.parse(sqlite.data.rows.public_source_snapshots[0][2]);assert.equal(snapshot.snapshot.id,payload.snapshot.id);assert.equal(snapshot.snapshot.content_fingerprint,payload.snapshot.content_fingerprint);
   const store=openStore(dir+'/store',binding);try{store.backup(dir+'/journal-archive.json');}finally{store.close();}
   const business=source.exportRows(),schema=JSON.parse(await readFile(new URL('../schema/manifest.json',import.meta.url),'utf8'));
   const components={'wordpress-files':{files:wp.files,images:wp.images},mariadb:{database:wp.database,images:wp.images,excluded:wp.excluded},'scanner-sqlite':sqlite,'publisher-journal':JSON.parse(await readFile(dir+'/journal-archive.json','utf8')),'native-business':{ids:source.ids,tables:business,schema,security:source.security(),images:source.images,identity_policy:'Only stable synthetic UUID linkage; native GoTrue admin API creates fresh users with new random credentials/JWT secret. No Auth password/session/refresh/key bytes.'}};
   source.assertNoSecrets(JSON.stringify(components));const archive=dir+'/backup',backup=pack(archive,checkpoint,components);verify(archive,backup.sha256);
   // Refusals happen before any target resource starts. Preserve original archive throughout.
   const negatives=[];
   assert.throws(()=>newTarget(archive,dir,backup.sha256),/new absent target/);negatives.push('existing target refused');
   for(const mode of ['missing','hash','mixed']){const bad=dir+'/bad-'+mode;cpSync(archive,bad,{recursive:true});chmodSync(bad,0o700);if(mode==='missing')rmSync(bad+'/mariadb.json');else if(mode==='hash')writeFileSync(bad+'/mariadb.json','broken');else{const p=bad+'/mariadb.json',c=JSON.parse(readFileSync(p));c.checkpoint_id=randomUUID();const b=JSON.stringify(c)+'\n';writeFileSync(p,b);const m=JSON.parse(readFileSync(bad+'/manifest.json'));m.components.mariadb.sha256=sha(b);m.components.mariadb.bytes=Buffer.byteLength(b);writeFileSync(bad+'/manifest.json',JSON.stringify(m));}const digest=mode==='mixed'?sha(readFileSync(bad+'/manifest.json')):backup.sha256;assert.throws(()=>newTarget(bad,dir+'/refused-'+mode,digest),/Incomplete|checksum|Mixed/);assert.equal(existsSync(dir+'/refused-'+mode),false);negatives.push(mode+' rejected');}
   writePrivate(dir+'/store/writer.lock','{"pid":0}\n');const lock=readFileSync(dir+'/store/writer.lock');assert.throws(()=>settledJournal(dir+'/store/journal.json',binding),/crash lock/);assert.throws(()=>openStore(dir+'/store',binding));assert.deepEqual(readFileSync(dir+'/store/writer.lock'),lock);negatives.push('persistent crash lock retained');
   // Source containers and TLS broker are destroyed before any target native service starts.
   await site.close();await source.close();assert.equal(host.child.exitCode,0);
   const sourceExitedAt=new Date().toISOString(),recovered=newTarget(archive,target,backup.sha256),c=recovered.components;
   assert.deepEqual(c['native-business'].schema,schema);for(const [file,digest] of Object.entries(schema.hashes))assert.equal(sha(await readFile(new URL('../schema/'+file,import.meta.url))),digest);
   targetNative=await nativeFixture({ids:c['native-business'].ids,restore:c['native-business'].tables});assert.notEqual(targetNative.run,source.run);checkCatalog(targetNative.sql,false);assert.deepEqual(targetNative.images,c['native-business'].images);assert.deepEqual(targetNative.security(),c['native-business'].security);
   const oldTokenStatus=(await targetNative.call(targetNative.authOrigin,'/user',{token:session.access_token})).status;assert.ok([401,403].includes(oldTokenStatus));assert.equal((await targetNative.call(targetNative.authOrigin,'/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}})).status,400);
   targetSite=await createThemedSite();assert.notEqual(targetSite.run,site.run);assert.deepEqual(targetSite.pages,site.pages);const ta=wpRecovery(targetSite);ta.pause();assert.notDeepEqual(ta.capture().database,c.mariadb.database);ta.restore({...c.mariadb,files:c['wordpress-files'].files});ta.assertClosed();const recaptured=ta.capture();assert.deepEqual(recaptured.database,c.mariadb.database);assert.deepEqual(recaptured.files,c['wordpress-files'].files);ta.unpause();assert.deepEqual(ta.snapshot(),exactPages);assert.deepEqual(targetSite.controls(),controls);for(const slug of ['about','privacy'])assert.equal(sha((await targetSite.call('/'+slug+'/',{authenticated:false})).text),htmlBefore[slug]);assert.equal(targetSite.attempts(),2);
   assert.ok([401,403].includes((await targetSite.call(targetSite.path(targetSite.target))).status));
   const sqliteBytes=Buffer.from(c['scanner-sqlite'].base64,'base64');assert.equal(sha(sqliteBytes),c['scanner-sqlite'].sha256);writePrivate(target+'/scanner.sqlite',sqliteBytes);const recoveredSQLite=sqliteSnapshot(target+'/scanner.sqlite',target+'/sqlite-check.sqlite');assert.deepEqual(recoveredSQLite.data,c['scanner-sqlite'].data);
   writePrivate(target+'/journal.json',JSON.stringify(c['publisher-journal'])+'\n');const journalRestore=restoreBackup(target+'/journal.json',target+'/store',binding);assert.equal(journalRestore.mode,'readonly');
   const native=async(url,o={})=>{const u=new URL(url);assert.equal(u.origin,backend);const auth=u.pathname==='/auth/v1/user',path=auth?'/user':u.pathname.slice(8)+u.search;assert.ok(auth||u.pathname.startsWith('/rest/v1/'));const r=await targetNative.call(auth?targetNative.authOrigin:targetNative.restOrigin,path,{method:o.method??'GET',token:new Headers(o.headers).get('authorization')?.slice(7),body:o.body?JSON.parse(o.body):undefined});return {status:r.status,ok:r.status>=200&&r.status<300,json:async()=>r.data};};
   let targetWPCalls=0;const closedSite={...targetSite,call:async()=>{targetWPCalls++;throw Error('Restored target has no WP read/write authority');}};
   targetHost=await childHost({config:{...config,storage_directory:target+'/store',write_grant:null,read_grant:null},site:closedSite,fetchImpl:native});targetGateway=await wiringFixture({site:targetSite,database:target+'/scanner.sqlite',publication_origin:targetHost.origin,recoveryReadOnly:true});
   const fresh=await targetNative.login('owner');assert.notEqual(fresh.access_token,session.access_token);const state=targetNative.exportRows();assert.deepEqual(state,business);assert.equal(targetGateway.quiescence().scanner_pid,null);assert.deepEqual(await targetHost.dispatch(fresh.access_token,'history',{version_id:saved.id}),history);
   for(const action of ['preview','publish','restore','readback'])await assert.rejects(targetHost.dispatch(fresh.access_token,action,{version_id:saved.id,intent_id:operations[0].id,page_id:site.target,confirm:true}));assert.equal(targetWPCalls,0);
   const save={p_organization_id:source.ids.org,p_opportunity_id:saved.opportunity_id,p_request_id:randomUUID(),p_expected_version:1,p_payload:payload};assert.ok([403,404].includes((await targetNative.call(targetNative.restOrigin,'/rpc/save_url_result_draft',{method:'POST',token:fresh.access_token,body:save})).status));
   for(const actor of ['viewer','foreign']){const a=await targetNative.login(actor),rows=await targetNative.call(targetNative.restOrigin,'/content_versions?id=eq.'+saved.id,{token:a.access_token});assert.equal(rows.status,200);assert.equal(rows.data.length,actor==='viewer'?1:0);await assert.rejects(targetHost.dispatch(a.access_token,'history',{version_id:saved.id}));}
   const errors=[];targetContext=await browser.newContext({viewport:{width,height:844},serviceWorkers:'block'});const page=await targetContext.newPage();page.on('pageerror',e=>errors.push(e.message));
   await targetContext.route('**/*',async route=>{try{const req=route.request(),u=new URL(req.url());if(u.origin==='http://127.0.0.1:8791')return route.fulfill(await targetGateway.route(req));if(u.origin==='https://rc-source.example'){const r=await targetSite.call(u.pathname+u.search,{authenticated:false});return route.fulfill({status:r.status,contentType:'text/html; charset=utf-8',body:r.text});}assert.equal(u.origin,backend);const r=await native(req.url(),{method:req.method(),headers:req.headers(),body:req.method()==='POST'?req.postData():undefined});return route.fulfill({status:r.status,contentType:'application/json',body:JSON.stringify(await r.json())});}catch(e){errors.push(e.message);return route.abort();}});
   for(const item of targetSite.pack.pages){await page.goto('https://rc-source.example'+item.path);assert.equal(await page.title(),item.title);assert.equal(await page.locator('meta[name="description"]').getAttribute('content'),item.meta_description);assert.equal(await page.locator('[itemtype="https://schema.org/Product"]').count(),item.kind==='product'?1:0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#main-content').evaluate(e=>e===document.activeElement),true);await page.screenshot({path:'/tmp/'+run+'-recovery-'+width+'-'+item.slug+'.png',fullPage:true});}
   await enterWorkspaceSession(page,{origin:'http://127.0.0.1:8791',access_token:fresh.access_token,expires_in:fresh.expires_in});assert.deepEqual(await page.evaluate(async()=>{const c=await import('/url-result-config.mjs');return {save:c.urlSaveEnabled,review:c.urlReviewEnabled,schema:c.urlResultSchemaEnabled};}),{save:false,review:false,schema:true});const view=page.locator(`.typed-version[data-version-id="${saved.id}"]`);await view.locator('.typed-loader > summary').click();await view.locator('.typed-draft').waitFor();assert.deepEqual(JSON.parse(await view.locator('.typed-draft > details').last().locator('pre').textContent()).payload,payload);await view.locator('.wp-history').focus();await page.keyboard.press('Enter');await view.locator('.wp-status').filter({hasText:'已恢復發布前內容'}).waitFor();await view.locator('.measurement-read').click();await view.locator('.measurement-status').filter({hasText:'量測已讀回'}).waitFor();assert.match(await view.locator('.measure-followup-result').innerText(),/未知（不是零）/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/'+run+'-recovery-'+width+'-history.png',fullPage:true});
   assert.deepEqual(errors,[]);assert.deepEqual(targetNative.exportRows(),state);assert.equal(targetWPCalls,0);assert.equal(targetSite.attempts(),2);ta.assertClosed();checkCatalog(targetNative.sql,false);assert.deepEqual(readFileSync(dir+'/store/writer.lock'),lock);verify(archive,backup.sha256);
   const proof={width,checkpoint,manifest_sha256:backup.sha256,components:backup.manifest.components,source_processes_exited_at:sourceExitedAt,target_native:targetNative.run,target_wordpress:targetSite.run,fresh_native_session:true,all_14_business_tables_exact:true,writer_acl_closed:true,default_acl_and_ensure_rls_exact:true,old_tokens_and_refresh_rejected:true,old_access_token_status:oldTokenStatus,old_wp_credentials_and_grants_not_restored:true,source_wp_posts:posts,target_publisher_wp_calls:targetWPCalls,target_scanner_process_started:false,wp_attempt_count:targetSite.attempts(),wordpress_files_exact:true,fresh_target_before_database_different:true,controls_html_exact:true,wordpress_database_sanitized_exact:true,pages_raw_meta_controls_exact:true,scanner_sqlite_integrity_and_rows_exact:true,scanner_snapshot_count:sqlite.data.rows.public_source_snapshots.length,history_exact:true,review_exact:true,measurement_unknown_not_zero:true,tenant_and_readonly_denials:true,refusals:negatives,crash_lock_preserved:true,no_secrets:true,limits:wp.excluded};
   source.assertNoSecrets(JSON.stringify(proof));targetNative.assertNoSecrets(JSON.stringify(proof));cpSync(archive,'/tmp/'+run+'-'+width+'-backup',{recursive:true});chmodSync('/tmp/'+run+'-'+width+'-backup',0o700);await writeFile('/tmp/'+run+'-recovery-'+width+'-manifest.json',JSON.stringify(backup.manifest,null,2)+'\n',{mode:0o600});return proof;
  }finally{await targetContext?.close();await targetGateway?.close();await targetHost?.close();await targetSite?.close();await targetNative?.close();}
 }
};}
