import test from 'node:test';
import assert from 'node:assert/strict';
import {createW1Api} from '../../apps/web/w1-workspace-api.mjs';
const org='00000000-0000-4000-8000-000000000001',product='00000000-0000-4000-8000-000000000002',actor='00000000-0000-4000-8000-000000000003';
const config={origin:'https://wqepyttadrcnphtyjpjy.supabase.co',key:'sb_publishable_fixture',redirectOrigin:'https://w1.example.invalid',productId:product,accessEnabled:true,writerEnabled:true};
const fragment='#access_token=synthetic-token&token_type=bearer&expires_in=3600';
function rig({user={id:actor},members=[{organization_id:org,role:'owner'}],now=()=>0,state=[{id:product,organization_id:org}]}={}){const calls=[];const api=createW1Api(config,{now,fetchImpl:async(url,options)=>{calls.push({url,options});const data=url.includes('/auth/v1/user')?user:url.includes('/r7_members?')?members:url.includes('/w1_state?')?state:{};return new Response(JSON.stringify(data));}});return {api,calls};}
test('closed/wrong project/non-publishable key/wrong product cannot make any network calls',async()=>{for(const change of [{accessEnabled:false},{origin:'https://wrong.supabase.co'},{key:'service-secret'},{productId:'not-uuid'}]){let calls=0;const api=createW1Api({...config,...change},{fetchImpl:()=>{calls++;throw Error('unexpected');}});await assert.rejects(api.authenticate(fragment));await assert.rejects(api.requestMagicLink('owner@example.invalid'));assert.equal(calls,0);}});
test('invalid link, unverified user, missing/ambiguous/nonmember role remain signed out',async()=>{for(const altered of [{user:{}},{members:[]},{members:[{organization_id:org,role:'admin'}]},{members:[{organization_id:org,role:'owner'},{organization_id:org,role:'viewer'}]}]){const {api}=rig(altered);await assert.rejects(api.authenticate(fragment));assert.equal(api.context(),null);await assert.rejects(api.request('state'));}for(const hash of ['#access_token=x','#error=bad&access_token=x&token_type=bearer&expires_in=1','#access_token=x&token_type=bearer&expires_in=-1']){const {api}=rig();await assert.rejects(api.authenticate(hash));}});
test('native verified user filters existing DB membership; marker is not JWT; no caller role accepted',async()=>{const {api,calls}=rig();await api.authenticate(fragment);assert.equal(new URL(calls[1].url).searchParams.get('user_id'),'eq.'+actor);assert.equal((await api.request('login',{method:'POST',body:{actor:'foreign'}})).access_token,'verified-session');assert.equal(api.context().role,'owner');await api.request('state');for(const {options} of calls){assert.equal(options.redirect,'error');assert.equal(options.credentials,'omit');}await assert.rejects(api.request('history?product='+actor),{status:403});await assert.rejects(api.request('answer',{method:'POST',body:{p_org:actor,p_product:product,p_request:actor}}),{status:403});});
test('expiry/logout and late authentication cannot recreate session',async()=>{let clock=0;const {api}=rig({now:()=>clock});await api.authenticate(fragment);clock=3600001;await assert.rejects(api.request('state'),{status:401});assert.equal(api.context(),null);let release;const gate=new Promise(r=>release=r);const late=createW1Api(config,{fetchImpl:async()=>{await gate;return new Response(JSON.stringify({id:actor}));}});const pending=late.authenticate(fragment);late.clear();release();await assert.rejects(pending);assert.equal(late.context(),null);});
test('OTP uses exact new canonical callback, existing account only, never automatically retries',async()=>{const {api,calls}=rig();await api.requestMagicLink('owner@example.invalid');assert.equal(calls.length,1);assert.equal(new URL(calls[0].url).searchParams.get('redirect_to'),config.redirectOrigin+'/w1-workspace');assert.deepEqual(JSON.parse(calls[0].options.body),{email:'owner@example.invalid',create_user:false});await assert.rejects(api.requestMagicLink('owner@example.invalid'));assert.equal(calls.length,1);});
test('server scope discrepancy is rejected, writer false preserves reads and blocks POST',async()=>{const {api}=rig({state:[{id:product,organization_id:actor}]});await api.authenticate(fragment);await assert.rejects(api.request('state'),{status:403});let calls=0;const readonly=createW1Api({...config,writerEnabled:false},{fetchImpl:async(url)=>{calls++;return new Response(JSON.stringify(url.includes('/user')?{id:actor}:url.includes('r7_members')?[{organization_id:org,role:'owner'}]:[]));}});await readonly.authenticate(fragment);const before=calls;await assert.rejects(readonly.request('answer',{method:'POST',body:{p_org:org,p_product:product,p_request:actor}}),{status:403});assert.equal(calls,before);});
function statusRig(){let clock=1000,server={product_id:product,server_time_ms:1000,expires_at_ms:61000,answer_allowed:false,review_allowed:false,answers_remaining:0,reviews_remaining:0};const calls=[];const api=createW1Api(config,{now:()=>clock,fetchImpl:async(url,options)=>{calls.push({url,method:options.method});if(url.includes('/auth/v1/user'))return new Response(JSON.stringify({id:actor}));if(url.includes('/r7_members?'))return new Response(JSON.stringify([{organization_id:org,role:'owner'}]));if(url.includes('/w1_writer_status?'))return server instanceof Response?server:new Response(JSON.stringify(server));return new Response(JSON.stringify({request_id:actor}));}});return {api,calls,set:s=>server=s,clock:t=>clock=t,open:()=>({...server,answer_allowed:true,review_allowed:true,answers_remaining:2,reviews_remaining:2})};}
test('fixed UI flag cannot open closed DB; native status unlocks same session and expiry closes locally',async()=>{const r=statusRig();await r.api.authenticate(fragment);assert.equal(r.api.canWrite(),false);await r.api.refreshWriteStatus();assert.equal(r.api.canWrite(),false);r.set(r.open());await r.api.refreshWriteStatus();assert.equal(r.api.canWrite('answer'),true);assert.equal(r.calls.filter(x=>x.url.includes('/auth/v1/user')).length,1);r.clock(61001);assert.equal(r.api.canWrite(),false);assert.equal(r.calls.filter(x=>x.method==='POST').length,0);});
test('every mutation first reads current status; revocation/error/bad product prevents POST',async()=>{for(const failure of [new Response('{}',{status:500}),{product_id:actor,server_time_ms:1000,expires_at_ms:61000,answer_allowed:true,review_allowed:true,answers_remaining:2,reviews_remaining:2},{product_id:product,server_time_ms:1000,expires_at_ms:61000,answer_allowed:false,review_allowed:false,answers_remaining:0,reviews_remaining:0}]){const r=statusRig();await r.api.authenticate(fragment);r.set(r.open());await r.api.refreshWriteStatus();assert.equal(r.api.canWrite(),true);r.set(failure);await assert.rejects(r.api.request('answer',{method:'POST',body:{p_org:org,p_product:product,p_request:actor,p_expected:0,p_source:1,p_value:'yes'}}),{status:403});assert.equal(r.api.canWrite(),false);assert.equal(r.calls.filter(x=>x.method==='POST').length,0);}});
test('quota is per kind, status GET cannot grant beyond its expiry, success is never replayed',async()=>{const r=statusRig();await r.api.authenticate(fragment);r.set({...r.open(),answers_remaining:1,reviews_remaining:0,review_allowed:false});await r.api.refreshWriteStatus();assert.equal(r.api.canWrite('answer'),true);assert.equal(r.api.canWrite('review'),false);await r.api.request('answer',{method:'POST',body:{p_org:org,p_product:product,p_request:actor,p_expected:0,p_source:1,p_value:'yes'}});assert.equal(r.api.canWrite('answer'),false);assert.equal(r.calls.filter(x=>x.method==='POST').length,1);});
test('late status after logout cannot reopen UI or send mutation',async()=>{let release;const gate=new Promise(r=>release=r);const api=createW1Api(config,{fetchImpl:async url=>{if(url.includes('/user'))return new Response(JSON.stringify({id:actor}));if(url.includes('/r7_members'))return new Response(JSON.stringify([{organization_id:org,role:'owner'}]));await gate;return new Response(JSON.stringify({product_id:product,server_time_ms:1000,expires_at_ms:61000,answer_allowed:true,review_allowed:true,answers_remaining:2,reviews_remaining:2}));}});await api.authenticate(fragment);const pending=api.refreshWriteStatus();api.clear();release();await assert.rejects(pending);assert.equal(api.context(),null);assert.equal(api.canWrite(),false);});
