import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const dir='delivery/w1-private/dist/';await mkdir(dir,{recursive:true});
const files=['first-result.css','product-fact.css','w1-workspace-api.mjs','w1-workspace-config.mjs','w1-workspace-boot.mjs','r7-workspace-api.mjs','intro-save.mjs','intro-r7-review.mjs','intro-candidate.mjs'];
for(const file of files)await writeFile(dir+file,await readFile('apps/web/'+file));
let html=await readFile('apps/web/product-fact.html','utf8');
html=html.replace("connect-src 'self'", "connect-src https://wqepyttadrcnphtyjpjy.supabase.co").replace('隔離工程驗證','產品工作區').replace(/<h2>隔離工作區<\/h2>.*?<p id="auth-status" role="status">.*?<\/p>/,'<h2>產品工作區</h2><p>以既有帳號登入；資料與操作資格由工作區驗證。</p><input id="actor" type="hidden" value="viewer"><form id="email-form"><label for="email">電子郵件</label><input id="email" type="email" autocomplete="email" required><button id="send-link" type="submit">寄送登入連結</button></form><button id="login" hidden>讀取工作區</button><button id="logout" hidden>登出本頁</button><p id="auth-status" role="status">工作區尚未開放。</p>');
html=html.replaceAll('./','/w1-assets/');
await writeFile(dir+'index.html',html);
let ui=await readFile('apps/web/product-fact.mjs','utf8');
ui=ui.replace('// W1 isolated surface: same-origin runner only; no hosted configuration or browser persistence.',"import {hostedFetch,boot} from './w1-workspace-boot.mjs';").replace("fetch('/w1/'+path,",'hostedFetch(path,').replace('已驗證原生隔離 Auth 身分；答案由隔離 PostgreSQL 保存。','已驗證既有 Auth 與工作區資格；寫入仍受伺服器窗口限制。').replace("$('login').hidden=false;","$('login').hidden=true;$('email-form').hidden=false;").replace("$('logout').hidden=false;","$('logout').hidden=false;$('email-form').hidden=true;");
await writeFile(dir+'product-fact.mjs',ui+'\nawait boot();\n');
assert.deepEqual((await readdir(dir)).sort(),[...files,'index.html','product-fact.mjs'].sort(),'Unexpected file in closed deployment package');
const manifest={};for(const f of (await readdir(dir)).sort())manifest[f]=createHash('sha256').update(await readFile(dir+f)).digest('hex');await writeFile('delivery/w1-private/SHA256.json',JSON.stringify(manifest,null,2)+'\n');
