import assert from 'node:assert/strict';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
import {nativeFixture} from '../../prototype/private-site/recovery/native-fixture.mjs';
import {createW1Api} from '../../apps/web/w1-workspace-api.mjs';
const dir='supabase/drafts/product_fact/pilot/',files={};
for(const [name,hash] of Object.entries(JSON.parse(await readFile(dir+'SHA256.json','utf8')))){files[name]=await readFile(dir+name,'utf8');assert.equal(createHash('sha256').update(files[name]).digest('hex'),hash);}
const manifest=JSON.parse(await readFile('delivery/w1-private/SHA256.json','utf8'));
assert.deepEqual((await readdir('delivery/w1-private/dist')).sort(),Object.keys(manifest).sort());
for(const [name,hash] of Object.entries(manifest))assert.equal(createHash('sha256').update(await readFile('delivery/w1-private/dist/'+name)).digest('hex'),hash);
for(const file of Object.keys(manifest).filter(x=>x.endsWith('.mjs'))){const source=await readFile('delivery/w1-private/dist/'+file,'utf8');for(const match of source.matchAll(/from ['"]\.\/([^'"]+)['"]/g))assert.ok(Object.hasOwn(manifest,match[1]),'Missing import: '+file+' -> '+match[1]);}
const checks=[],ok=s=>{checks.push(s);console.log('PASS W1 pilot '+s);};
let calls=0;const closed=createW1Api({}, {fetchImpl:()=>{calls++;throw Error('closed network');}});assert.equal(closed.available(),false);await assert.rejects(closed.authenticate('#access_token=fake&token_type=bearer&expires_in=3600'));await assert.rejects(closed.requestMagicLink('owner@example.invalid'));assert.equal(calls,0);ok('closed config has zero network; exact SQL and static manifest hashes');
const n=await nativeFixture(),product=randomUUID(),sessions=[];let browser;
const scope={p_org:n.ids.org,p_product:product};
const rpc=(fn,token,body)=>n.call(n.restOrigin,'/rpc/'+fn,{method:'POST',token,body});
const answer=(expected,value='yes')=>({...scope,p_request:randomUUID(),p_expected:expected,p_source:1,p_value:value});
const state=async token=>{const r=await n.call(n.restOrigin,'/w1_state?id=eq.'+product,{token});assert.equal(r.status,200);return r.data[0];};
const snapshot=()=>n.sql("select jsonb_build_object('facts',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from w1_facts x),'drafts',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from w1_drafts x),'reviews',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from w1_reviews x),'requests',(select coalesce(jsonb_agg(to_jsonb(x) order by request_id),'[]') from w1_requests x),'gate',(select to_jsonb(g) from w1_private.gate g))");
const r7Snapshot=()=>n.sql("select jsonb_build_object('catalog',(select jsonb_agg(jsonb_build_object('name',c.relname,'acl',c.relacl::text,'rls',c.relrowsecurity,'options',c.reloptions) order by c.relname) from pg_class c where c.relnamespace='r7_private'::regnamespace or c.oid='public.r7_members'::regclass),'functions',(select jsonb_agg(pg_get_functiondef(p.oid) order by p.oid) from pg_proc p where p.pronamespace='r7_private'::regnamespace or (p.pronamespace='public'::regnamespace and p.proname in ('save_r7_intro','confirm_r7_intro'))),'policies',(select jsonb_agg(to_jsonb(p) order by policyname) from pg_policies p where schemaname='r7_private'),'gate',(select to_jsonb(g) from r7_private.write_gate g),'members',(select jsonb_agg(to_jsonb(m) order by user_id) from r7_private.members m),'counts',array[(select count(*) from r7_private.versions),(select count(*) from r7_private.confirmations),(select count(*) from r7_private.audit)])");
async function until(fn){for(let i=0;i<150;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50));}throw Error('native barrier timed out');}
function session(app){const p=spawn('docker',['exec','-i','-e','PGAPPNAME='+app,'--user','postgres',n.run+'-db','psql','-XAtq','-U','postgres','-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'],{stdio:['pipe','pipe','pipe']});let out='',err='';p.stdout.on('data',b=>out+=b);p.stderr.on('data',b=>err+=b);const done=new Promise(r=>p.once('close',code=>r({code,out,err})));sessions.push(p);return {p,done,ready:()=>out.includes('READY')};}
const blocked=(h,w)=>until(()=>n.sql(`select exists(select 1 from pg_stat_activity a,pg_stat_activity b where a.application_name='${h}' and b.application_name='${w}' and a.pid=any(pg_blocking_pids(b.pid)))`)==='t');
const actor=`begin;set local statement_timeout='15s';set local role authenticated;select set_config('request.jwt.claim.sub','${n.ids.owner}',true);`;
const saveSql=expected=>`select public.w1_change('${n.ids.org}','${product}','${randomUUID()}',${expected},1,'yes');`;
// Test-fixture administration only: fresh independent window conditions; never deploy this helper.
const resetWindow=()=>n.sql("update w1_private.gate set enabled=true,expires_at=clock_timestamp()+interval '5 minutes',answers=0,reviews=0;grant execute on function public.w1_change(uuid,uuid,uuid,integer,integer,text),public.w1_review(uuid,uuid,uuid,uuid),w1_private.w1_change_impl(uuid,uuid,uuid,integer,integer,text),w1_private.w1_review_impl(uuid,uuid,uuid,uuid) to authenticated;notify pgrst,'reload schema';");
try{
 n.sql(await readFile('supabase/drafts/r7_intro/proposal.sql','utf8'));
 n.sql(`insert into r7_private.members values('${n.ids.owner}','${n.ids.org}','owner'),('${n.ids.viewer}','${n.ids.org}','viewer'),('${n.ids.foreign}','${n.ids.other}','owner');grant usage on schema r7_private to authenticated;grant select on r7_private.members,public.r7_members to authenticated;`);
 const r7Before=r7Snapshot();n.sql(files['preflight.sql']);n.sql(files['install.sql']);n.sql(files['postflight.sql']);
 const owner=await n.login('owner'),viewer=await n.login('viewer'),foreign=await n.login('foreign');
 await until(async()=>[401,403].includes((await n.call(n.restOrigin,'/w1_state?select=*',{token:owner.access_token})).status));
 assert.equal(n.sql("select enabled from w1_private.gate"),'f');assert.equal(n.sql("select has_function_privilege('authenticated','public.w1_change(uuid,uuid,uuid,integer,integer,text)','EXECUTE')"),'f');
 n.sql(`select set_config('w1.actor_id','${n.ids.owner}',false),set_config('w1.organization_id','${n.ids.org}',false),set_config('w1.product_id','${product}',false);`+files['enroll-readonly.sql']);
 await until(async()=>(await n.call(n.restOrigin,'/w1_state?select=*',{token:owner.access_token})).status===200);
 assert.equal((await state(owner.access_token)).answer,'unknown');let before=snapshot();assert.equal((await rpc('w1_change',owner.access_token,answer(0))).status,403);assert.equal(snapshot(),before);ok('install closed; separate readonly enrollment; no write before enable');
 n.sql("select set_config('w1.expires_at',(clock_timestamp()+interval '5 minutes')::text,false);"+files['enable.sql']);
 await until(()=>n.sql("select has_function_privilege('authenticated','public.w1_change(uuid,uuid,uuid,integer,integer,text)','EXECUTE')")==='t');
 before=snapshot();assert.ok([401,403].includes((await n.call(n.restOrigin,'/w1_state?select=*')).status));assert.equal((await n.call(n.restOrigin,'/w1_state?select=*',{token:owner.access_token.slice(0,-8)+'invalid!'})).status,401);for(const who of [viewer,foreign])assert.equal((await rpc('w1_change',who.access_token,answer(0))).status,403);
 assert.equal((await rpc('w1_change',owner.access_token,{...answer(0),p_product:randomUUID()})).status,403);
 assert.equal((await rpc('w1_change',owner.access_token,{...answer(0),p_org:n.ids.other})).status,403);
 for(const t of ['w1_products','w1_facts','w1_drafts','w1_reviews','w1_requests'])assert.equal((await n.call(n.restOrigin,'/'+t,{method:'POST',token:owner.access_token,body:{}})).status,403);
 assert.equal(snapshot(),before);assert.equal(await state(foreign.access_token),undefined);assert.equal((await state(viewer.access_token)).answer,'unknown');ok('native owner/viewer/foreign membership; wrong scope and direct writes denied, zero delta');
 const first=answer(0);assert.equal((await rpc('w1_change',owner.access_token,first)).status,200);before=snapshot();assert.equal((await rpc('w1_change',owner.access_token,first)).status,200);assert.equal(snapshot(),before);
 let current=await state(owner.access_token);assert.equal(current.confirmed_by,n.ids.owner);
 assert.equal((await rpc('w1_review',owner.access_token,{...scope,p_request:randomUUID(),p_draft:current.draft_id})).status,200);
 assert.equal((await rpc('w1_change',owner.access_token,answer(1,'no'))).status,200);current=await state(owner.access_token);assert.equal(current.review_valid,false);
 assert.equal((await rpc('w1_review',owner.access_token,{...scope,p_request:randomUUID(),p_draft:current.draft_id})).status,200);
 before=snapshot();assert.equal((await rpc('w1_change',owner.access_token,answer(2))).status,403);assert.equal((await rpc('w1_review',owner.access_token,{...scope,p_request:randomUUID(),p_draft:current.draft_id})).status,403);assert.equal(snapshot(),before);ok('single verified actor/product; exact replay before quota; two-answer/two-review hard limit');
 // Late INSERT lock crosses deadline; final admission check rolls all business rows back.
 resetWindow();n.sql("update w1_private.gate set expires_at=clock_timestamp()+interval '2 seconds'");before=snapshot();const h=session('w1-late-holder'),w=session('w1-late-writer');h.p.stdin.write("begin;lock table w1_requests in share mode;select 'READY';\n");await until(h.ready);w.p.stdin.end(actor+saveSql(2)+'commit;\n');await blocked('w1-late-holder','w1-late-writer');await until(()=>n.sql('select expires_at<=clock_timestamp() from w1_private.gate')==='t');h.p.stdin.end('commit;\n');assert.equal((await h.done).code,0);const late=await w.done;assert.notEqual(late.code,0);assert.match(late.err,/42501/);assert.equal(snapshot(),before);ok('native late-DML deadline rolls back fact/draft/request/counter atomically');
 // Disable owns gate first. A queued writer sees committed closure and cannot mutate.
 resetWindow();const d=session('w1-disabler'),queued=session('w1-queued');d.p.stdin.write("begin;update w1_private.gate set enabled=false;select 'READY';\n");await until(d.ready);const dataBefore=n.sql('select count(*) from w1_requests');queued.p.stdin.end(actor+saveSql(2)+'commit;\n');await blocked('w1-disabler','w1-queued');d.p.stdin.end('commit;\n');assert.equal((await d.done).code,0);const denied=await queued.done;assert.notEqual(denied.code,0);assert.match(denied.err,/42501/);assert.equal(n.sql('select count(*) from w1_requests'),dataBefore);ok('native queued writer observes committed gate closure');
 resetWindow();const admitted=session('w1-admitted'),closing=session('w1-closing');admitted.p.stdin.write(actor+saveSql(2)+"select 'READY';\n");await until(admitted.ready);closing.p.stdin.end(files['disable.sql']);await blocked('w1-admitted','w1-closing');admitted.p.stdin.end('commit;\n');assert.equal((await admitted.done).code,0);assert.equal((await closing.done).code,0);assert.equal(n.sql('select enabled from w1_private.gate'),'f');assert.equal((await rpc('w1_change',owner.access_token,answer(3))).status,403);
 const exactClosed=await state(owner.access_token);const fresh=await n.login('owner');assert.deepEqual(await state(fresh.access_token),exactClosed);assert.throws(()=>n.sql("select set_config('w1.expires_at',(clock_timestamp()+interval '5 minutes')::text,false);"+files['enable.sql']),/already consumed/);ok('disable waits for admitted transaction, revokes write ACL, preserves fresh native readback; no re-enable');
 // Adapter uses real isolated native Auth and R7 membership. Never contact the hosted project.
 const config={origin:'https://wqepyttadrcnphtyjpjy.supabase.co',key:'sb_publishable_isolated',redirectOrigin:'https://w1.example.invalid',productId:product,accessEnabled:true,writerEnabled:true};
 const nativeFetch=async(url,opts)=>{const u=new URL(url);assert.equal(u.origin,config.origin);const target=u.pathname.startsWith('/auth/v1/')?n.authOrigin+u.pathname.slice(8)+u.search:n.restOrigin+u.pathname.slice(8)+u.search;assert.ok(u.pathname.startsWith('/auth/v1/')||u.pathname.startsWith('/rest/v1/'));return fetch(target,opts);};
 const fragment=s=>'#'+new URLSearchParams({access_token:s.access_token,token_type:'bearer',expires_in:'3600'});
 const adapter=createW1Api(config,{fetchImpl:nativeFetch});await adapter.authenticate(fragment(fresh));assert.equal(adapter.context().role,'owner');assert.equal((await adapter.request('state'))[0].id,product);await assert.rejects(adapter.request('answer',{method:'POST',body:{...answer(3),p_org:n.ids.other}}),{status:403});
 const vAdapter=createW1Api(config,{fetchImpl:nativeFetch});await vAdapter.authenticate(fragment(viewer));assert.equal(vAdapter.context().role,'viewer');await assert.rejects(vAdapter.request('answer',{method:'POST',body:answer(3)}),{status:403});adapter.clear();await assert.rejects(adapter.request('state'),{status:401});ok('formal adapter verifies native Auth + DB membership, blocks injected scope/viewer, clears session');
 browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined});
 for(const width of [1280,390]){
  resetWindow();let context,page,posts=0;const errors=[];
  async function open({enabled=true,role='owner',writer=true}={}){await context?.close();context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'});
  await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin===config.redirectOrigin){const file=u.pathname==='/w1-workspace'?'index.html':u.pathname.replace(/^\/w1-assets\//,'');if(!Object.hasOwn(manifest,file))return route.abort();const data=file==='w1-workspace-config.mjs'&&enabled?'export default '+JSON.stringify({...config,writerEnabled:writer}):await readFile('delivery/w1-private/dist/'+file);return route.fulfill({status:200,contentType:file.endsWith('.mjs')?'text/javascript':file.endsWith('.css')?'text/css':'text/html',body:data});}if(u.origin===config.origin){posts+=req.method()==='POST'?1:0;const response=await nativeFetch(req.url(),{method:req.method(),headers:req.headers(),...(req.postData()?{body:req.postData()}:{}),redirect:'error'});return route.fulfill({status:response.status,headers:{'content-type':'application/json','access-control-allow-origin':config.redirectOrigin},body:await response.text()});}return route.abort();});page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('W1 UI error:',e.message);});const session=enabled?await n.login(role):null;await page.goto(config.redirectOrigin+'/w1-workspace'+(session?fragment(session):''));if(enabled)await page.locator('#result').waitFor();else await page.locator('#email-form').waitFor({state:'hidden'});}
  await open({enabled:false});assert.equal(posts,0);assert.equal(await page.locator('#email-form').isVisible(),false);assert.equal(await page.locator('select#actor').count(),0);
  await open();assert.equal(await page.evaluate(()=>location.hash),'');await page.locator('#correct').click();await page.locator('#answer').selectOption('no');await page.locator('#save').click();await page.locator('#feedback').filter({hasText:'已保存答案'}).waitFor();await page.locator('#review-check').check();await page.locator('#review').click();await page.locator('#state').filter({hasText:'此確切版已確認'}).waitFor();const exact=await state(owner.access_token);assert.equal(posts,2);await page.locator('#logout').click();await page.locator('#result').waitFor({state:'hidden'});
  await open();assert.deepEqual(await state(owner.access_token),exact);await page.locator('#state').filter({hasText:'此確切版已確認'}).waitFor();assert.equal(posts,2);assert.equal(await page.locator('#answer-form').isVisible(),false);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(await context.cookies(),[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/w1-pilot-'+width+'.png',fullPage:true});
  n.sql(files['disable.sql']);await open({writer:false});assert.equal(await page.locator('#correct').isVisible(),false);assert.equal(await page.locator('#review-panel').isVisible(),false);assert.deepEqual(await state(owner.access_token),exact);await open({role:'viewer'});assert.equal(await page.locator('#correct').isVisible(),false);assert.deepEqual(errors,[]);await context.close();ok('UI '+width+': closed default, no actor selector, native login/save/review/logout/fresh readback; closed writer + viewer readonly, no storage/overflow');
 }
 assert.equal(r7Snapshot(),r7Before);ok('R7 catalog/ACL/policies/membership/gate/history unchanged throughout');
 await writeFile('/tmp/w1-pilot-evidence.json',JSON.stringify({result:'PASS',environment:'isolated native PG17/GoTrue/PostgREST; synthetic only; no hosted requests',checks},null,2));
}finally{for(const p of sessions)if(p.exitCode===null){p.stdin.destroy();p.kill('SIGTERM');}await browser?.close();await n.close();}
