import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {start} from './runner.mjs';
const rig=await start({mode:'w1-isolated'});const {native:n,productIds:p}=rig;let browser;
let lastPage;const checks=[];const ok=name=>{checks.push(name);console.log('PASS '+name);};
const rpc=(name,token,body)=>n.call(n.restOrigin,'/rpc/'+name,{method:'POST',token,body});
const state=async(token,product)=>{const r=await n.call(n.restOrigin,'/w1_state?select=*&id=eq.'+product,{token});assert.equal(r.status,200);return r.data[0];};
const body=(product,expected,source,value)=>({p_org:n.ids.org,p_product:product,p_request:randomUUID(),p_expected:expected,p_source:source,p_value:value});
const snapshot=()=>n.sql("select jsonb_build_object('facts',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from w1_facts x),'drafts',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from w1_drafts x),'reviews',(select coalesce(jsonb_agg(to_jsonb(x) order by id),'[]') from w1_reviews x),'requests',(select coalesce(jsonb_agg(to_jsonb(x) order by request_id),'[]') from w1_requests x))");
try{
 let owner=await n.login('owner'),viewer=await n.login('viewer'),foreign=await n.login('foreign');
 let save=body(p.a,0,1,'yes');assert.equal((await rpc('w1_change',owner.access_token,save)).status,200);let a=await state(owner.access_token,p.a);assert.equal(a.answer,'yes');
 const review={p_org:n.ids.org,p_product:p.a,p_request:randomUUID(),p_draft:a.draft_id};assert.equal((await rpc('w1_review',owner.access_token,review)).status,200);assert.equal((await state(owner.access_token,p.a)).review_valid,true);
 assert.equal(a.fact_source_quote,a.source_quote);assert.equal(a.fact_market,a.market);assert.equal(a.confirmed_by,n.ids.owner);
 const oldDraft=a.draft_id,before=snapshot();assert.equal((await rpc('w1_change',owner.access_token,save)).status,200);assert.equal(snapshot(),before);assert.equal((await rpc('w1_change',owner.access_token,{...save,p_value:'no'})).status,400);
 assert.equal((await rpc('w1_change',owner.access_token,body(p.a,1,1,'no'))).status,200);a=await state(owner.access_token,p.a);assert.equal(a.fact_version,2);assert.equal(a.answer,'no');assert.equal(a.review_valid,false);assert.notEqual(a.draft_id,oldDraft);assert.equal(n.sql(`select count(*) from w1_drafts where id='${oldDraft}'`),'1');assert.equal((await state(owner.access_token,p.b)).fact_version,0);assert.equal((await state(owner.access_token,p.market)).fact_version,0);ok('atomic answer/new draft/current-review invalidation; immutable old version; unrelated product/market unchanged; exact replay');
 assert.equal((await rpc('w1_review',owner.access_token,{...review,p_request:randomUUID()})).status,409);
 const base=snapshot();for(const who of [viewer,foreign])assert.equal((await rpc('w1_change',who.access_token,body(p.a,2,1,'yes'))).status,403);
 assert.equal(await state(foreign.access_token,p.a),undefined);assert.equal((await state(viewer.access_token,p.a)).answer,'no');
 for(const t of ['w1_products','w1_facts','w1_drafts','w1_reviews','w1_requests'])assert.equal((await n.call(n.restOrigin,'/'+t,{method:'POST',token:owner.access_token,body:{}})).status,403);
 assert.equal(snapshot(),base);ok('native Auth/RLS owner/viewer/foreign; direct table writes denied with zero delta');
 // Force a late request-insert failure: answer and draft must roll back together.
 const rollbackBefore=snapshot();n.sql("alter table w1_requests add constraint w1_force_rollback check(input->>'value'<>'yes') not valid");
 assert.equal((await rpc('w1_change',owner.access_token,body(p.a,2,1,'yes'))).status,400);assert.equal(snapshot(),rollbackBefore);n.sql('alter table w1_requests drop constraint w1_force_rollback');
 // Anonymous, forged JWT, direct mutation and invalid payload do not change history.
 assert.ok([401,403].includes((await n.call(n.restOrigin,'/w1_state?select=*')).status));
 assert.equal((await n.call(n.restOrigin,'/w1_state?select=*',{token:owner.access_token.slice(0,-8)+'invalid!'})).status,401);
 for(const method of ['PATCH','DELETE'])assert.equal((await n.call(n.restOrigin,'/w1_facts?id=eq.'+a.fact_id,{method,token:owner.access_token,body:method==='PATCH'?{value:'yes'}:undefined})).status,403);
 assert.equal((await rpc('w1_change',owner.access_token,body(p.a,2,1,'unknown'))).status,400);assert.equal(snapshot(),rollbackBefore);
 const catalog=JSON.parse(n.sql("select jsonb_agg(jsonb_build_object('name',proname,'definer',prosecdef,'anon',has_function_privilege('anon',oid,'execute'),'service',has_function_privilege('service_role',oid,'execute'),'config',proconfig)) from pg_proc where proname like 'w1_%'"));assert.equal(catalog.length,4);assert.ok(catalog.every(f=>!f.anon&&!f.service&&f.config.includes('search_path=\"\"')));assert.ok(catalog.filter(f=>!f.name.endsWith('_impl')).every(f=>!f.definer));
 ok('late failure rolls back answer/draft/request atomically; anonymous/forged JWT/direct update/delete denied; skip cannot erase confirmed fact; closed privileged function ACL');
 // Two native PostgREST connections race with the same expected base.
 const race=await Promise.all(['yes','no'].map(value=>rpc('w1_change',owner.access_token,body(p.a,2,1,value))));assert.deepEqual(race.map(x=>x.status).sort(),[200,409]);a=await state(owner.access_token,p.a);assert.equal(a.fact_version,3);ok('concurrent saves: one winner, stale writer rejected without partial facts/drafts');
 // Save and exact Review race on the same product row. Either order leaves only current facts approvable.
 const rbody={p_org:n.ids.org,p_product:p.a,p_request:randomUUID(),p_draft:a.draft_id};
 const coupled=await Promise.all([rpc('w1_review',owner.access_token,rbody),rpc('w1_change',owner.access_token,body(p.a,3,1,a.answer==='yes'?'no':'yes'))]);
 assert.ok([200,409].includes(coupled[0].status));assert.equal(coupled[1].status,200);a=await state(owner.access_token,p.a);assert.equal(a.fact_version,4);assert.equal(a.review_valid,false);ok('concurrent review/answer serialized; stale approval never current after answer commit');
 // Serialize source updates and review with the same product lock, preserving merchant value.
 n.sql(`update w1_products set observed_outdoor='${a.answer==='yes'?'no':'yes'}',source_version=2 where id='${p.a}'`);const conflicted=await state(owner.access_token,p.a);assert.equal(conflicted.answer,a.answer);assert.equal(conflicted.is_conflict,true);assert.equal(conflicted.review_valid,false);
 assert.equal((await rpc('w1_review',owner.access_token,{...review,p_request:randomUUID(),p_draft:a.draft_id})).status,409);assert.equal((await rpc('w1_change',owner.access_token,body(p.a,4,1,'yes'))).status,409);ok('source conflict preserves merchant answer; stale source and review rejected');
 // Native logout, new server JWT, precise DB readback; old refresh revoked.
 const previous=owner;assert.equal((await n.call(n.authOrigin,'/logout?scope=local',{method:'POST',token:previous.access_token})).status,204);assert.equal((await n.call(n.authOrigin,'/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:previous.refresh_token}})).status,400);owner=await n.login('owner');assert.notEqual(owner.access_token,previous.access_token);assert.deepEqual(await state(owner.access_token,p.a),conflicted);ok('native logout/revoked refresh/new JWT/exact immutable answer + dependent draft readback');
 browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined});
 for(const width of [1280,390]){
  // Different untouched product/market per viewport avoids rewriting prior evidence.
  const product=width===1280?p.b:p.market;let context,page;const errors=[];
  async function fresh(role='owner'){await context?.close();context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===rig.origin?r.continue():r.abort());page=await context.newPage();lastPage=page;page.on('pageerror',e=>errors.push(e.message));await page.goto(rig.origin+'/product-fact.html');await page.locator('#actor').selectOption(role);await page.locator('#login').click();await page.locator('#result').waitFor();await page.locator('#product').selectOption(product);await page.locator('#product-name').filter({hasText:width===1280?'合成產品 B':'合成產品 A'}).waitFor();}
  await fresh();assert.match(await page.locator('.badge').textContent(),/Synthetic.*非真 AI/);await page.locator('#skip').focus();await page.keyboard.press('Enter');await page.locator('#feedback').filter({hasText:'答案仍未知'}).waitFor();let v=await state(owner.access_token,product);assert.equal(v.answer,'unknown');assert.equal(v.source_kind,'skipped_unknown');assert.equal(v.confirmed_by,null);assert.equal(v.confirmed_at,null);assert.equal(v.fact_version,1);
  await page.locator('#review-check').focus();await page.keyboard.press('Space');await page.locator('#review').focus();await page.keyboard.press('Enter');await page.locator('#state').filter({hasText:'此確切版已確認'}).waitFor();
  rig.dropNext('answer');const posts=rig.posts();await page.locator('#answer').selectOption('yes');await page.locator('#save').focus();await page.keyboard.press('Enter');await page.locator('#feedback').filter({hasText:'結果待核對'}).waitFor();assert.equal(rig.posts(),posts+1);assert.equal(await page.locator('#save').isDisabled(),true);await page.locator('#reconcile').click();await page.locator('#feedback').filter({hasText:'舊確認已失效'}).waitFor();assert.equal(rig.posts(),posts+1);v=await state(owner.access_token,product);assert.equal(v.fact_version,2);assert.equal(v.review_valid,false);assert.equal(await page.locator('#answer-form').isVisible(),false);assert.equal(await page.locator('#review-check').isChecked(),false);
  rig.dropNext('review');const reviewPosts=rig.posts();await page.locator('#review-check').check();await page.locator('#review').click();await page.locator('#feedback').filter({hasText:'結果待核對'}).waitFor();await page.locator('#reconcile').click();await page.locator('#state').filter({hasText:'此確切版已確認'}).waitFor();assert.equal(rig.posts(),reviewPosts+1);const exact=await state(owner.access_token,product);
  await page.locator('#logout').click();await page.locator('#result').waitFor({state:'hidden'});await fresh();assert.deepEqual(await state(owner.access_token,product),exact);await page.locator('#state').filter({hasText:'答案第 2 版'}).waitFor();assert.equal(await page.locator('#answer-form').isVisible(),false);assert.match(await page.locator('#draft').textContent(),/支援戶外使用/);await page.locator('summary').click();await page.locator('#history p').nth(1).waitFor();assert.equal(await page.locator('#history p').count(),2);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(await context.cookies(),[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/w1-product-fact-'+width+'.png',fullPage:true});
  await page.locator('#correct').click();await page.locator('#answer').selectOption('no');await page.locator('#save').click();await page.locator('#feedback').filter({hasText:'第 3 版'}).waitFor();assert.equal((await state(owner.access_token,product)).review_valid,false);// A source update makes the page's captured base stale; definitive 409 keeps the input and allows read recovery.
  await page.locator('#correct').click();await page.locator('#answer').selectOption('yes');n.sql(`update w1_products set source_version=2 where id='${product}'`);await page.locator('#save').click();await page.locator('#feedback').filter({hasText:'此操作已拒絕'}).waitFor();assert.equal(await page.locator('#answer').inputValue(),'yes');assert.equal(await page.locator('#refresh').isDisabled(),false);assert.equal((await state(owner.access_token,product)).fact_version,3);await page.locator('#refresh').click();await page.locator('#state').filter({hasText:'來源已變更'}).waitFor();
  await fresh('viewer');assert.equal(await page.locator('#correct').isVisible(),false);assert.equal(await page.locator('#review-panel').isVisible(),false);assert.deepEqual(errors,[]);await context.close();ok('UI '+width+': keyboard skip/answer/save/review; lost replies GET-only; logout/fresh native login/exact readback; no reasking; correction invalidates; viewer readonly; no overflow/storage');
 }
 await writeFile('/tmp/w1-product-fact-evidence.json',JSON.stringify({result:'PASS',environment:'isolated native PG17/GoTrue/PostgREST, synthetic data, no hosted or model calls',checks},null,2));
}catch(e){if(lastPage)console.error('UI diagnostic',await lastPage.locator('#feedback').textContent(),await lastPage.locator('#state').textContent());throw e;}finally{try{await browser?.close();}finally{await rig.close();}}
