// Test runner only. No fixture import or transport override in production startup.
import http from 'node:http';
import {spawn} from 'node:child_process';
import {createHandler} from './gateway.mjs';
export const candidateBackend='https://wqepyttadrcnphtyjpjy.supabase.co';
export async function wiringFixture({site,database,publication_origin,recoveryReadOnly=false}){
 const origin='http://127.0.0.1:8791';let python,gateway,wpBridge,closed=false;const routes={},wpCalls={GET:0,POST:0};
 const bridge=http.createServer(async(req,res)=>{try{if(req.method!=='GET'||!['/robots.txt','/growth-os/'].includes(req.url))throw Error('denied');const r=await site.call(req.url,{authenticated:false});res.writeHead(r.status,{'content-type':req.url==='/robots.txt'?'text/plain':'text/html'});res.end(r.text);}catch{res.writeHead(403);res.end();}});
 const listen=s=>new Promise((r,j)=>{s.once('error',j);s.listen(0,'127.0.0.1',r);});await listen(bridge);
 wpBridge=http.createServer(async(req,res)=>{try{const allowed=req.url===site.path(site.target)||['/growth-os/','/robots.txt','/about/','/privacy/'].includes(req.url);if(!allowed)throw Error('denied');let body='';for await(const b of req)body+=b;const r=await site.call(req.url,{method:req.method,...(body?{body:JSON.parse(body)}:{}),authenticated:Boolean(req.headers.authorization),headers:req.headers['x-growth-before']?{'x-growth-before':req.headers['x-growth-before']}:{}});res.writeHead(r.status,{'content-type':req.url.startsWith('/?')?'application/json':'text/html'});res.end(r.text);}catch{res.writeHead(403);res.end();}});await listen(wpBridge);
 async function close(){if(closed)return;closed=true;if(wpBridge){wpBridge.closeAllConnections();await new Promise(r=>wpBridge.close(r));}if(gateway){gateway.closeAllConnections();await new Promise(r=>gateway.close(r));}if(python&&python.exitCode===null){const exit=new Promise(r=>python.once('exit',r));python.kill('SIGTERM');await exit;}bridge.closeAllConnections();await new Promise(r=>bridge.close(r));}
 try{
 let port=1;
 if(!recoveryReadOnly){python=spawn('python3',['-B',new URL('./source-fixture.py',import.meta.url).pathname],{stdio:['pipe','pipe','pipe']});let errors='';python.stderr.on('data',b=>errors+=b);
 const ready=new Promise((resolve,reject)=>{let out='';python.stdout.on('data',b=>{out+=b;if(out.includes('\n'))resolve(JSON.parse(out.split('\n')[0]).port);});python.once('error',reject);python.once('exit',()=>reject(Error('Source HTTP fixture stopped '+errors)));});
 python.stdin.end(JSON.stringify({mode:'growth-os-isolated-regression',url:site.targetURL,bridge:'http://127.0.0.1:'+bridge.address().port,database})+'\n');
 port=await ready;}
 const config={enabled:true,public_origin:origin,supabase:{origin:candidateBackend,publishable_key:'sb_publishable_synthetic',allowed_origins:[candidateBackend]},source_origin:'http://127.0.0.1:'+port,publication_origin,activation:{approval_reference:'synthetic-owned-run',expires_at:Date.now()+300000,save_review_rpcs:['review_url_result','save_url_result_draft'],publisher:true},wordpress:{origin:'https://rc-source.example',upstream:'http://127.0.0.1:'+wpBridge.address().port,page_id:site.target}};
 const handler=await createHandler(config);gateway=http.createServer((req,res)=>{if(recoveryReadOnly&&req.url==='/url-result-config.mjs'){res.writeHead(200,{'content-type':'text/javascript','cache-control':'no-store'});return res.end('export const urlResultSchemaEnabled=true,urlSaveEnabled=false,urlSaveTrial=null,urlReviewSchemaEnabled=true,urlReviewEnabled=false,urlReviewTrial=null;');}if(recoveryReadOnly&&(req.url==='/api/product-source'||/^\/api\/wordpress-publication\/(preview|publish|restore|readback|measurement-save)$/.test(req.url))){res.writeHead(503);return res.end();}return handler(req,res);});await listen(gateway);
 async function siteCall(path,o={}){wpCalls[o.method??'GET']++;return new Promise((resolve,reject)=>{const body=o.body?JSON.stringify(o.body):null;const r=http.request({hostname:'127.0.0.1',port:gateway.address().port,path,method:o.method??'GET',headers:{host:'rc-source.example',...(o.authenticated===false?{}:{authorization:'Basic c3ludGhldGljOnJ1bg=='}),...(body?{'content-type':'application/json','content-length':Buffer.byteLength(body)}:{}),...o.headers}},res=>{let text='';res.on('data',b=>text+=b);res.on('end',()=>resolve({status:res.statusCode,text,json:()=>JSON.parse(text)}));});r.on('error',reject);r.end(body);});}
 return {close,siteCall,quiescence:()=>({gateway_closed:closed,scanner_pid:python?.pid??null,scanner_exited:!python||python.exitCode!==null||python.signalCode!==null}),proof:()=>({routes,wordpress_proxy_calls:wpCalls,supabase_origin:candidateBackend,transport:'candidate handler over owned loopback HTTP; separate contracts verify TLS CLI',source:'unchanged Python handle_product with owned network fixture',auth:'synthetic sessions and isolated SQL; no live Supabase'}),async route(req){const u=new URL(req.url());routes[u.pathname]=(routes[u.pathname]??0)+1;return new Promise((resolve,reject)=>{const r=http.request({hostname:'127.0.0.1',port:gateway.address().port,path:u.pathname+u.search,method:req.method(),headers:{...req.headers(),host:new URL(origin).host}},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));});r.on('error',reject);r.end(req.method()==='POST'?req.postData():undefined);});}};
 }catch(e){await close();throw e;}
}
