-- UNAPPROVED OFFLINE CANDIDATE. Execute only under a separately approved action envelope.
DO $persistent_review$ BEGIN
if exists(select 1 from pg_proc p cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.oid in ('public.save_url_result_draft(uuid,uuid,uuid,integer,jsonb)'::regprocedure,'private.save_url_result_draft_impl(uuid,uuid,uuid,integer,jsonb)'::regprocedure,'public.save_first_result_draft(uuid,uuid,uuid,integer,jsonb)'::regprocedure,'private.save_first_result_draft_impl(uuid,uuid,uuid,integer,jsonb)'::regprocedure) and a.grantee=0 and a.privilege_type='EXECUTE') or exists(select 1 from (values('anon'),('authenticated'),('service_role')) acl_role(name) cross join (values('public.save_url_result_draft(uuid,uuid,uuid,integer,jsonb)'::regprocedure),('private.save_url_result_draft_impl(uuid,uuid,uuid,integer,jsonb)'::regprocedure),('public.save_first_result_draft(uuid,uuid,uuid,integer,jsonb)'::regprocedure),('private.save_first_result_draft_impl(uuid,uuid,uuid,integer,jsonb)'::regprocedure)) f(id) where has_function_privilege(acl_role.name,f.id,'EXECUTE')) then raise exception 'Expected closed effective ACL'; end if;
 if exists(select 1 from (values('anon'),('authenticated')) r(name) where has_table_privilege(r.name,'public.audit_events','INSERT,UPDATE,DELETE,TRUNCATE')) or exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where c.oid='public.audit_events'::regclass and a.grantee=0 and a.privilege_type in ('INSERT','UPDATE','DELETE','TRUNCATE')) then raise exception 'Audit effective write ACL must be closed'; end if;
 if (select encode(sha256(convert_to(prosrc,'UTF8')),'hex') from pg_proc where oid=to_regprocedure('private.save_url_result_draft_impl(uuid,uuid,uuid,integer,jsonb)')) is distinct from 'e7c41525d87e0bc0b6b5d25d73e319df16054bb05155a821ddd15f7d9bb054e1' then raise exception 'Closed Save body drift'; end if;
 if exists(select 1 from (values('authenticated'),('anon')) r(name) cross join (values('public.content_reviews'),('public.content_versions'),('public.growth_opportunities')) t(name) where has_table_privilege(r.name,t.name,'INSERT,UPDATE,DELETE,TRUNCATE')) then raise exception 'Unexpected direct table write'; end if;
 if exists(select 1 from pg_policies where schemaname='public' and tablename='audit_events' and cmd<>'SELECT') then raise exception 'Unexpected audit write policy'; end if;
 if exists(select 1 from pg_roles where rolname in ('authenticated','anon') and (rolsuper or rolbypassrls)) or exists(select 1 from pg_class where oid in ('public.content_reviews'::regclass,'public.content_versions'::regclass,'public.growth_opportunities'::regclass,'public.audit_events'::regclass) and not relrowsecurity) then raise exception 'Auth role or RLS drift'; end if;
 if (select count(*) from supabase_migrations.schema_migrations)<>24 then raise exception 'Expected 24 records after approved audit revoke; reconcile drift before installation'; end if;
 if (select count(*) from supabase_migrations.schema_migrations where name='url_review_persistent_audit_revoke' and array_length(statements,1)=1 and encode(sha256(convert_to(statements[1],'UTF8')),'hex')='edaeb2bf54b4de7a3d56d679cfcebf07597efb0065500333a9db2bb4a574c17b')<>1 then raise exception 'Exact tracked audit revoke record required'; end if;
 if to_regprocedure('public.review_url_result(uuid,uuid,uuid,text,text,text,jsonb)') is not null or to_regprocedure('private.review_url_result_impl(uuid,uuid,uuid,text,text,text,jsonb)') is not null or exists(select 1 from information_schema.columns where table_schema='public' and table_name='content_reviews' and column_name like 'url_review_%') or exists(select 1 from pg_constraint where conrelid='public.content_reviews'::regclass and conname in ('content_reviews_url_request_unique','content_reviews_url_shape')) then raise exception 'Review already installed or partial schema; reconcile, never replay install'; end if;
END $persistent_review$;
